NYPL/digital-research-books

CHANGELOG.md
config/development.yaml
config/example.yaml
config/qa.yaml
processes/hathiTrust.py
processes/nypl.py
tests/helper.py
tests/unit/test_hathitrust_process.py
tests/unit/test_nypl_process.py

Two of the daily ingesters -- for HathiTrust and NYPL records -- relied on a `datetime` format that was misconfigured regarding time zones. This corrects the issue to allow for accurate fetching of records over the past 24 hours.
This also adds some additional conditions to the NYPL process. Previously the ingest process fetched all research bibs updated in the past 24 hours, but that group includes primarily non-open sourced recently published works, which are no the focus of DRB. The process now checks the publication date and only takes pre-95 years ago records and records up to 1964 if we can be somewhat confident in their copyright status. This utilizes, in a very conservative way, the Bardo CCE API to make that determination, and which defaults to assume that work is copyrighted. …

SFR-228 Fix Daily Ingesters

---

CHANGELOG.md
managers/oclcClassify.py
mappings/oclcCatalog.py
mappings/oclcClassify.py
processes/oclcClassify.py
tests/unit/test_oclcClassify_manager.py
tests/unit/test_oclcClassify_mapping.py
tests/unit/test_oclcClassify_process.py

This adds a new condition that allows the `OCLCClassify` process to page through large Work records retrieved from the classify service. Each page is limited to 500 edition records, so this allows for fetching of larger sets of edition records and thereby improving the accuracy of the DRB records for that work.

NOREF Extend Classify Fetching

---

CHANGELOG.md
api/elastic.py
managers/sfrElasticRecord.py
managers/sfrRecord.py
tests/unit/test_api_es.py
tests/unit/test_sfrElastic_manager.py
tests/unit/test_sfrRecord_manager.py

This is a somewhat minor PR that resolves several bugs in the indexing process:
- Add ability to define default role for agents in ElasticSearch manager
- Clean up dates as they are processed to remove duplicate values
- Fix regression in API with ElasticSearch aggregation

NOREF Indexing Fixes

---

CHANGELOG.md
README.md
main.py
managers/gutenberg.py
mappings/gutenberg.py
processes/api.py
processes/developmentSetup.py
processes/gutenberg.py
processes/hathiTrust.py
processes/nypl.py
processes/oclcCatalog.py
processes/oclcClassify.py
processes/s3Files.py
processes/sfrCluster.py
tests/unit/test_gutenberg_manager.py
tests/unit/test_gutenberg_mapping.py
tests/unit/test_gutenberg_process.py
tests/unit/test_main_process.py

This adds two new parameters to the main invocation process: `limit` and `offset`. These allow for processed to be batched, which is useful when testing and doing bulk loading of data. The impetus for this was the need to rate limit the Gutenberg ingest process due to restrictions on the GitHub GraphQL API, but it will likely prove to be useful in other areas as well.
This also adds the "exploded" versions of Gutenberg ePub files for use by the webpub reader. This also generally improves the handling of the epub ingest process and handles errors better.

NOREF Gutenberg batched imports and epub manifests

---

CHANGELOG.md
mappings/hathitrust.py
processes/hathiTrust.py
tests/unit/test_hathitrust_process.py

This improves error handling in the HathiTrust process through a small refactor that moves the iteration of the CSV file into its own method. This allows for error handling for individual rows, and prevents a case where a single malformed row could block and entire import.

NOREF HathiTrust Error Handling Improvements

---

CHANGELOG.md
managers/s3.py
processes/s3Files.py
tests/unit/test_s3_manager.py
tests/unit/test_sfrFile_process.py

This adds a performance boost to the storing of files in S3 by allowing several threads to run in parallel.
This also includes a naive fix to timeout issue that was being encountered with a very small number of large ePub files (generally 100 MB+). These were causing timeouts because of the long download/upload times. The process now detects these large files and omits them. This is not ideal but allows for a smoother overall process.

NOREF Add multiprocessing to S3 Process

---

processes/nypl.py
tests/unit/test_nypl_process.py

Adding `LIMIT` and `OFFSET` as optional parameters to the PostgreSQL query allows us to load all relevant records from the NYPL catalog in a controlled manner. This should also be useful for re-running records in the future if necessary.

NOREF Add limit and offset to NYPL import

---

processes/oclcClassify.py
tests/unit/test_oclcClassify_process.py

This allows the classify process to be run in batches of arbitrary size. This will not be used in the daily import process but provides useful functionality when running large (or complete) custom import jobs. It allows for the control of records going to the Catalog service, which is rate limited.

NOREF Add batching to limit size of Classify Process

---

CHANGELOG.md
managers/rabbitmq.py
mappings/nypl.py
processes/nypl.py
processes/s3Files.py
tests/unit/test_rabbitmq_manager.py

This PR fixes to issues uncovered while testing the ingest process:
1) The rabbitMQ process was timing out during long running processes (large file uploads, etc.). This adds a `heartbeat` parameter to the rabbitMQ client to hold it open while processes execute
2) The NYPL ingest process was encountering errors when processing edge cases in the MARC metadata attached to these records. These cases have been handled by providing default values when expected fields are missing.

NOREF Ingest Fixes

---

CHANGELOG.md
README.md
config/development.yaml
config/example.yaml
config/qa.yaml
managers/__init__.py
managers/pdfManifest.py
mappings/marc.py
mappings/muse.py
processes/__init__.py
processes/muse.py
requirements.txt
tests/fixtures/muse_book_42.html
tests/fixtures/muse_book_63320.html
tests/helper.py
tests/unit/test_marc_mapping.py
tests/unit/test_muse_mapping.py
tests/unit/test_muse_process.py
tests/unit/test_pdf_chapter.py
tests/unit/test_pdf_manifest.py

This adds a process for ingesting Project MUSE records into the DRB database. This fetches MARC records for open access books available on Project MUSE. As these books are largely available as chapter-segmented PDF files, a manifest is constructed for each book that is used to provide access directly to the book content.
This process also adds a new mapping model for `MARC` records. This mapping assumes that the source records have already been parsed by `pymarc` or a similar library, the responsibility for which lies with individual processes. This is because MARC records are generally parsed as a batch, with some difficulty lying in the separation of individual records (hence the use of an external dependency).
To construct these PDF manifests the structure is inferred from the …

SFR-956 Add Project MUSE Process

---

CHANGELOG.md
managers/nyplApi.py
tests/unit/test_nyplAPI_manager.py

The recommended method of obtaining `refresh_token`s from the OAUTH server does not appear to work with the NYPL server (the tokens are not returned).
With no clear way to obtain these tokens a workaround is put in place here to:
1) Catch expired token errors
2) Fetch a new token from the token endpoint
3) Use that token to re-create the API client, retry the current query and store the new client for future calls
This also includes a performance improvement that blocks the manager from repeatedly creating new clients when not necessary.

SFR-984 NYPL API Fix

---

CHANGELOG.md
managers/s3.py
processes/s3Files.py
tests/unit/test_s3_manager.py
tests/unit/test_sfrFile_process.py

This implements two significant fixes for the s3 storage processes:
- First it implements a custom `Metadata` header on all files stored in s3 and uses this calculated value to check if the file has changed since it last changed. This makes it possible to skip uploads of unchaged files when records are reprocessed for metadata reasons
- Second a change to the size of the `byte_chunk`s that are used to upload these files. This was originally sent to 1024 bytes, which resulted in a huge number of chunks being processed and throttling the download/upload process. This has been increased to `1024 * 25` (250kb) which in testing proved to give good performance for both large and small files

SFR-985 Fix s3 Processes

---

CHANGELOG.md
mappings/gutenberg.py
processes/gutenberg.py
tests/unit/test_gutenberg_mapping.py
tests/unit/test_gutenberg_process.py

The new reader will not use the old JSON flags provided with each URI but instead use the media types attached as they are both easier to understand and a standard field. To support this we have settled on the `application/epub+xml` media type for the `container.xml` files that provide access to the structure of ePubs. This simply updates the Project Gutenberg process to match this new standard.

SFR-986 Update Gutenberg process to handle new media type

---

CHANGELOG.md
managers/parsers/frontierParser.py
managers/parsers/springerParser.py
processes/doab.py
processes/s3Files.py
tests/unit/test_parser_frontier.py
tests/unit/test_parser_springer.py
tests/unit/test_sfrFile_process.py

This implements several minor fixes for the DOAB ingest process, mainly to how ePub files are fetched from different publishers. These fixes are:
- Add an `User-Agent` header when fetching ePub files for s3 as some publishers expect it to be present
- Improve the Springer ingest by verifying that PDF and/or ePub files are present before attempting to store them
- Improve the Frontier parser by gracefully handling timeout errors
- Remove extraneous `print` statements and other QoL improvements

SFR-952 DOAB file fetch fixes

---

CHANGELOG.md
api/app.py
api/blueprints/__init__.py
api/blueprints/drbInfo.py
managers/redis.py
tests/unit/test_api_info_blueprint.py
tests/unit/test_redis_manager.py

This extends the API with a very basic status response object that verifies that the API is running and in what environment. This is useful when testing deployments and is probably good to have in general. It should be updated to include the current application version in the future.
Additionally, as the deployed versions of this application may share a redis cluster the keys that they generate should be specific to each environment (to avoid collisions). To do so each key is prefixed with the current environment which should avoid any issues.

SFR-958 Deployment Extensions

---

CHANGELOG.md
api/blueprints/drbSearch.py
api/blueprints/drbWork.py
api/elastic.py
api/utils.py
tests/unit/test_api_es.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py

This implements a number of improvements around the `showAll` filter option. These are:
- Standardize the paramater between the `search` and `work` endpoints: Use camelCase as a standalone parameter for both
- Extend the handling of the parameter in `elasticsearch` to ensure that it properly handles cases when the param is explicitly set to `false`
- Related test suite updates
This also generally ensures that all query and response parameters use `camelCase` instead of `snake_case` for consistency reasons.

SFR-975 API quality of life improvements

---

CHANGELOG.md
managers/doabParser.py
managers/parsers/abstractParser.py
managers/parsers/defaultParser.py
managers/parsers/degruyterParser.py
managers/parsers/frontierParser.py
managers/parsers/openEditionParser.py
managers/parsers/springerParser.py
managers/s3.py
model/postgres/link.py
processes/gutenberg.py
tests/unit/test_doab_link_manager.py
tests/unit/test_gutenberg_process.py
tests/unit/test_parser_default.py
tests/unit/test_parser_degruyter.py
tests/unit/test_parser_frontier.py
tests/unit/test_parser_openedition.py
tests/unit/test_parser_springer.py
tests/unit/test_s3_manager.py

This implements a number of necessary fixes for how files are fetched and stored from DOAB (some of these changes indirectly affect the Project Gutenberg ingest process). These updates are:
- Standardize the timeout value across DOAB sources
- Better handle timeout errors from DOAB sources
- Handle instances when `301` redirects only provide URL paths instead of full URLs
- Handle DOI based URLs from DeGruyter
- Allow s3 URLs to contain uppercase characters (necessary to match internal structure of ePub files)

NOREF DOAB ePub Fixes

---

CHANGELOG.md
Dockerfile
api/app.py
api/blueprints/drbInfo.py
api/blueprints/drbSearch.py
api/blueprints/drbWork.py
logger.py
main.py
processes/api.py
tests/unit/test_api_app.py

This moves the port at which the Flask application to `80` from the development port of `5000`. This works better with the ECS configuration and is likely the expected value.
This also adds an `EXPOSE` line to the Dockerfile, which is also necessary. When running the API localy it can still be access by passing `-p 5000:5000` to access the API.

SFR-960 Update Production Port

---

CHANGELOG.md
managers/elasticsearch.py
tests/unit/test_es_manager.py

This resolves a bug where the default python `urllib3` library is unable to parse AWS VPC URLs due to their length/unusual construction. By passing these parameters as a constructed string those checks can be bypassed and allow this manager to interact with those resources. (Which is necessary for the functioning of this cluster)

NOREF Fix ElasticSearch manager when using AWS ES Service

---

CHANGELOG.md
mappings/oclcCatalog.py
tests/unit/test_oclcCatalog_mapping.py

The OCLC Catalog mapping included a few bugs and had a few places where improvements could be made.
First, it was looking in the wrong subfield for the external resource URI (it needs to be set to subfield `u`). Second, it was not checking the first indicator for a value of `4` which denotes a reference to a resource.
The improvements are in the checking of validity of the links. This implements a new method to only allow Gutenberg, HathiTrust and InternetArchive links to be imported. Further this checks the IA links to be sure that they point to items that do not have restricted access. This method should be extended to further parse the Gutenberg and HathiTrust links as well, though that is less pressing.

NOREF Update OCLC Catalog link handling

---

managers/rabbitmq.py
managers/redis.py
managers/s3.py

Some processes load environment variables for managers that are never initialized. This updates those managers to gracefully handle missing environment variables. They will be initialized to null, which means if they are invoked they will raise errors, which is actually an intended side effect because they should not be invoked.

NOREF Improve Env var handling

---

.dockerignore
CHANGELOG.md
processes/gutenberg.py

This updates the Gutenberg process to handle invocations where a ingest limit and offset are not set (They default to `None` and a `TypeError` was being thrown).
This also adds a `.dockerignore` file to make the container build process somewhat cleaner

NOREF Container debugging

---

CHANGELOG.md
api/blueprints/drbSearch.py
api/db.py
api/utils.py
managers/coverFetchers/contentCafeFetcher.py
managers/coverFetchers/openLibraryFetcher.py
managers/db.py
managers/kMeans.py
managers/redis.py
managers/sfrRecord.py
processes/core.py
processes/covers.py
processes/hathiTrust.py
processes/muse.py
processes/nypl.py
processes/oclcClassify.py
processes/s3Files.py
processes/sfrCluster.py
tests/helper.py
tests/unit/test_api_db.py
tests/unit/test_core_process.py
tests/unit/test_cover_process.py
tests/unit/test_db_manager.py
tests/unit/test_fetcher_openlibrary.py
tests/unit/test_hathitrust_process.py
tests/unit/test_muse_process.py
tests/unit/test_nypl_process.py
tests/unit/test_oclcClassify_process.py
tests/unit/test_redis_manager.py
tests/unit/test_sfrRecord_manager.py

Running these processes on ECS means that they run in an environment where the containers have strict memory limits (controlled by the CloudFormation template for the stack). Several of the processes were found to exceed these limits for various reasons. Both for stability and performance these issues needed to be resolved. The individual fixes implemented are:
- An update in the NYPL process to allow for a database query to be streamed in chunks, rather than loaded all at once
- A change generally to the database layer to write updates more frequently and fully commit/flush the session more frequently
- Load HathiTrust CSV files without loading them to a temp file on disk, instead streaming them directly to a process
- Filter Project MUSE records for only records that need to be updated …

SFR-1006 ECS Memory Management Fixes

---

CHANGELOG.md
api/db.py
managers/coverFetchers/googleBooksFetcher.py
managers/coverFetchers/hathiFetcher.py
managers/kMeans.py
model/postgres/edition.py
model/postgres/item.py
model/postgres/record.py
model/postgres/work.py
processes/core.py
processes/covers.py
processes/hathiTrust.py
processes/oclcCatalog.py
processes/oclcClassify.py
tests/unit/test_core_process.py
tests/unit/test_cover_process.py
tests/unit/test_fetcher_hathitrust.py
tests/unit/test_kmeans_manager.py
tests/unit/test_oclcClassify_process.py

Real-world testing has revealed several issues with the interactions between the DRB application and its PostgreSQL database. This aims to resolve those issues by:
- Adding additional `CASCADE` constraints to foreign keys to allow records to be properly deleted by the `ClusterProcess`
- Update the bulk save operations code to prevent race conditions, particularly in the `OCLCClassifyProcess`
- Add additional indexes on several important columns

SFR-1012 Postgres Fixes

---

CHANGELOG.md
processes/sfrCluster.py
tests/unit/test_sfrCluster_process.py

Due to a information flow misjudgement the clustering stage was skipping clustering single record works. These are valid records that have no FRBRized data because they lack adequate identifiers or simply because they are rare. This should not disqualify them from being indexed and this update ensures that they are.

NOREF Fix Single Record Clustering

---

api/utils.py
mappings/nypl.py
tests/unit/test_api_utils.py
tests/unit/test_nypl_mapping.py

This updates NYPL bib records both on ingest and in the API response.
On ingest it updates the `media_type` values to `text/html` for catalog pages and to `application/x.html+edd` for EDD options. The second option here is temporary pending discussion and may be udpated later. This also fixes an error assigning some URLs to `nypl.com`
In the API response it sets a `location` value for item records for context with NYPL items and adds `item_id` and `edition_id` to the response for context as well

SFR-1007 Update NYPL records

---

CHANGELOG.md
api/app.py
api/blueprints/__init__.py
api/blueprints/drbEdition.py
api/blueprints/drbSearch.py
api/blueprints/drbUtils.py
api/blueprints/drbWork.py
api/db.py
api/elastic.py
api/utils.py
tests/unit/test_api_db.py
tests/unit/test_api_edition_blueprint.py
tests/unit/test_api_es.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py
tests/unit/test_api_utils_blueprint.py

This makes several important updates to the API, including bug fixes as well as new functionality. These are:
- Added a stand-alone Edition detail API endpoint
- Added Language and Record count utility endpoints
- Fixed a bug in when using the `showAll` parameter
- Added unique id fields to edition, item and link response objects
- Added `mediaType` field to link response object to provide context to the webreader

SFR-1010 Update API Response Links

---

CHANGELOG.md
managers/coverFetchers/hathiFetcher.py
managers/coverManager.py
managers/redis.py
processes/covers.py
tests/unit/test_cover_manager.py
tests/unit/test_cover_process.py
tests/unit/test_fetcher_hathitrust.py

The HathiTrust cover fetcher manager was throwing unexpected errors on malformed METS JSON records. This catches these errors and skips these malformed records.
This also adds a redis check for cover identifiers to prevent duplicate fetching of cover files when an identifier has already been queried

NOREF Hathi Cover Bugfix

---

managers/kMeans.py
managers/sfrRecord.py
mappings/hathitrust.py
processes/oclcClassify.py
processes/sfrCluster.py
tests/unit/test_kmeans_manager.py
tests/unit/test_sfrCluster_process.py
tests/unit/test_sfrRecord_manager.py

This implements several improvements to the clustering process that should both increase its accuracy and speed. This is achieved through several major changes:
- The "elbow" method of calculating the ideal value for K (the number of clusters to use) has been replaced with the `silhouette_score` method. Not only is this recommended by the developers of the `sklearn` module but it means replacing a large amount of custom code with a standard method call. Removing the opaque custom code (which performed fairly complex mathematical transformations) should make the process much more maintainable
- The means of traversing a set of `Record`s was previously linear, proceeding by regular intervals (which were dependent on the size of the collection). This has been replaced by a bisection method …

SFR-1026 Improved Grouping Traversal

---

CHANGELOG.md
managers/__init__.py
managers/smartsheet.py
processes/__init__.py
processes/ingestReport.py
requirements.txt
tests/helper.py
tests/unit/test_cover_process.py
tests/unit/test_ingestReport_process.py
tests/unit/test_smartsheet_manager.py

At the request of several people responsible for providing status updates on this project, it has been requested that we produce regular updates on the number of records available in DRB, as well as how many records we update/modify daily/weekly.
This adds this functionality by producing a simple report that is output to Smartsheet and which provides a daily snapshot of the database. This includes:
- Totals for `Work`, `Edition`, `Item` and `Record` records
- Counts for the number of created and modified records for each of the record types detailed above
- Highlighting of cells where data may be "anomalous" (exceeding 10% changed in a single day)

SFR-1019 Analytics Reporting

---

.github/workflows/build-qa.yaml
.github/workflows/tests.yaml
CHANGELOG.md

This adds new functionality to the Github Actions integration for this repo. Primarily this adds a deployment action that builds the docker image for this repository and deploys it to ECS. It also adds a step in the test action to ensure that the `CHANGELOG` has been updated.

NORFE Add GHA deployment action

---

CHANGELOG.md
api/db.py
api/elastic.py
managers/kMeans.py
managers/oclcClassify.py
managers/redis.py
managers/sfrRecord.py
processes/covers.py
processes/oclcClassify.py
processes/sfrCluster.py
tests/unit/test_api_db.py
tests/unit/test_api_es.py
tests/unit/test_cover_process.py
tests/unit/test_kmeans_manager.py
tests/unit/test_kmeans_yearobject.py
tests/unit/test_oclcClassify_process.py
tests/unit/test_redis_manager.py
tests/unit/test_sfrCluster_process.py
tests/unit/test_sfrRecord_manager.py

The core improvement in this PR is an update to the clustering process that both makes it faster and more accurate:
The accuracy improvements are:
- Changed the publication date clustering attribute from an integer representation to a dictionary representation(which includes century, decade and year). This improves accuracy by providing the algorithm a better estimation of the relative distance between dates
- Implemented a title check (based on the OCLC Work-Set Algorithm). This verifies that grouped records share a title with the source record if they are two or more steps away from that record
The speed improvements are:
- Reduced number of iterations used in each clustering step
- Reduced possible distance for records from source from 5 steps to 3
- Improved edition generation and …

NOREF Further Clustering Improvements

---

CHANGELOG.md
processes/covers.py
tests/unit/test_cover_process.py

The new release of SQLAlchemy is somewhat more strict in how it interprets SQL queries. This makes a minor modification to the main cover query to comply with this. A side effect is that the query is now somewhat simpler and should be clearer for future maintainers.

NOREF Update Cover query for SQLAlchemy 1.4

---

CHANGELOG.md
mappings/hathitrust.py
processes/sfrCluster.py
tests/unit/test_hathitrust_mapping.py
tests/unit/test_sfrCluster_process.py

In rare instances an identifier may contain a comma (either intentionally or unintentionally), this can cause issues in the clustering process as the constructed query will interpret an identifier that contains a comma as two seperate values to query. This is resolved by wrapping any such identifiers in quotation marks.
This also removes a source of potential commas in identifiers by splitting hathitrust identifiers on commas on ingest. Due to the format of hathitrust records in rare cases catalogers merged multiple identifiers into a single column. This ensures that we have more accurate data with which to cluster records

HOTFIX Handle identifiers with commas

---

CHANGELOG.md
api/app.py
api/blueprints/drbInfo.py
api/elastic.py
requirements.txt
swagger.v4.json
tests/unit/test_api_info_blueprint.py

This replaces the basic status endpoint at the API root with swagger documentation. This not only provides verification that the API is operational, but a useful guide to the endpoints and their responses. Currently this simply serves the endpoints without any prefixes but that could be updated to have a `v4` prefix.

SFR-1034 Add Swagger Documentation

---

CHANGELOG.md
api/elastic.py
api/utils.py
swagger.v4.json
tests/unit/test_api_es.py
tests/unit/test_api_utils.py

This makes two improvements to the API following early testing
1) The search query now handles multiple parameters of the same type in two ways: `query=title:Test&query=author:Test` and `query=title:Test,author:Test`
2) The search response block now includes both `language` and `format` facet blocks. The `format` block had been erroneously omitted previously

NOREF API Updates

---

CHANGELOG.md
managers/sfrRecord.py
processes/sfrCluster.py
static/iso639.json
static/manager.py
tests/unit/test_sfrCluster_process.py
tests/unit/test_sfrRecord_manager.py

In order to serve accurate data in the API two minor bugs were uncovered in the process of testing the API. These are:
- Removing empty strings from `rights` records to prevent issues with the `rights_date` column
- Handling ISO-639-2/b language codes. These have been depricated in ISO-639-3 but are still common in catalogs. A static mapping to more current terms has been added to handle these cases.

SFR-1041 Cluster Level Bugs

---

CHANGELOG.md
api/elastic.py
api/utils.py
managers/sfrRecord.py
processes/sfrCluster.py
tests/unit/test_api_es.py
tests/unit/test_api_utils.py
tests/unit/test_sfrCluster_process.py

This makes several improvements to increase the stability and usability of the API. These are:
- Fix erroneous object name in the ES DSL to allow for filtering on formats
- Fix "unsorting" regression following PostgreSQL query with search results
- Return only the year value for `publication_date` field on editions
- Gracefully handle some unexpected database errors

NOREF API Testing Bugfixes

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

The `links` block on editions was dropped in a regression and needs to be re-added so that cover links are present in API responses.

HOTFIX Ensure Cover links are present in edition records

---

CHANGELOG.md
api/blueprints/drbSearch.py
api/elastic.py
api/utils.py
managers/sfrRecord.py
tests/unit/test_api_es.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py
tests/unit/test_sfrRecord_manager.py

This implements a number of improvements and necessary fixes for the API to be released as `v0.5.1`. These are:
- Added a crosswalk between simple values that can be passed as URL parameters and the full `media_type` values as stored in the ElasticSearch index
- Handle related `400` Invalid request error with a custom response
- Add `edition_count` to API response
- Improve handling of unexpected characters in subject heading parsing

SFR-1042 Format Crosswalk + bugfixes

---

api/db.py
tests/unit/test_api_db.py

Fixes an erroneous update to improve query performance. Substitutes `options` for `option` and ensures that a full path for the join clause is present.

HOTFIX Resolve breaking error with sqlalchemy query construction

---

CHANGELOG.md
api/db.py
api/utils.py
managers/rabbitmq.py
tests/unit/test_api_db.py
tests/unit/test_api_utils.py
tests/unit/test_rabbitmq_manager.py

This bugfix commit includes two minor fixes to different aspects of the application.
- In the edition detail parser an erronous `publishers` reference is changed to `publisher`
- In the RabbitMQ client errors in connections are now handled for message receipt and acknowledgement, as well as generation.

NOREF Edition Detail and RabbitMQ fixes

---

CHANGELOG.md
api/db.py
api/utils.py
tests/unit/test_api_utils.py

This resolves two lingering issues in the edition detail endpoint:
- The method for parsing pipe delimited data did not anticipate `None` values and now handles those
- The eager loading for the Editions did not properly load `Item` links and rights objects. This was corrected

NOREF Resolve bugs in Edition detail endpoint

---

api/db.py

A setting in an effort to improve load times was causing the `edition_count` value to be incorrect. Removing an `options` call in the database query resolves the issue. This line was intended to improve performance, however removing seems to have a negligible, if any, impact on loading times.

HOTFIX Remove edition eager loading

---

CHANGELOG.md
managers/db.py
managers/oclcClassify.py
managers/rabbitmq.py
processes/oclcClassify.py
tests/unit/test_db_manager.py
tests/unit/test_oclcClassify_manager.py
tests/unit/test_oclcClassify_process.py
tests/unit/test_rabbitmq_manager.py

This includes a number of stability and performance bugfixes pertaining mainly to OCLC services. These are:
- Handle closed channel errors when processing OCLC Catalog records
- Skip Classify records that have already been processed for faster operation of the Classify process
- Handle database deadlocks in the classify process (which should be less common with the above improvements)

NOREF 20210410 bugfixes

---

CHANGELOG.md
processes/oclcClassify.py

These are two minor bugfixes to handle stability issues in the OCLC Classify Process.
- Deadlocks can be received when updating the status of queried records while classifying them. At present these updates are made individually, but due to improvements in the query process this is no longer necessary. Instead these records are added to the session and committed in a method that handles/retries when deadlocks are encontered. This obviates the need for additional deadlock handling.
- Adding an additional error class to an author parsing method. Previously this expected either a null value or an array of strings. This new condition also handles an array which contains null values.

NOREF 20210412 bugfixes

---

CHANGELOG.md
managers/parsers/abstractParser.py
managers/sfrRecord.py
mappings/doab.py
processes/doab.py
tests/unit/test_doab_mapping.py
tests/unit/test_doab_process.py
tests/unit/test_parser_abstract.py

A recent migration of the DOAB website and API required an update to the SFR ingest process to properly access these records. No longer are DOAB records published as full MARCXML records (only "stub" MARC records are now available), and instead the ingest process needs to harvest OAI_DC records. Fortunately these are also XML records and the overall data structure did not change too drastically, so this does not represent a huge difference. Importantly we are still able to parse records for the source of their ebook files and follow those paths to retrieve ePub and PDF representations of the books. In addition to the main conversion from MARCXML to OAI_DC, this work included:
- An update to the primary identifier for each record, which is now a DOI
- Simplification to some other fields, …

SFR-1022 Update DOAB to OAI_DC

---

CHANGELOG.md
mappings/core.py
processes/core.py
processes/oclcClassify.py
tests/unit/test_core_mapping.py

Investigations into the Classification process revealed several small tweaks that should improve performance:
- Adding an additional `ORDER BY` parameter to the windowed query method. This forces postgres to adequately plan/index these queries
- Prevent OCLC Catalog records from being classified, by definition these records are already classified

NOREF Classify Process Improvements

---

CHANGELOG.md
processes/sfrCluster.py
tests/unit/test_sfrCluster_process.py

While clustering records, the source records must be marked as processed (to avoid duplicating work). Previously this was done with a bare `update` statement. When running concurrently with other processes this can cause a deadlock in rare cases. This method was therefore refactored so that the `commit` can happen within a `try/except` block that handles the deadlock error.

NOREF Update Cluster Process committing

---

.github/workflows/tests-regression.yaml
CHANGELOG.md

Since tests run by allure-pytest will not have changes associated with each scheduled run, there is no need for Changelog requirement in Github workflow tests-regression.yaml.

Remove Changelog Requirement for Regression Tests

---

.github/workflows/build-branch-qa.yaml
.github/workflows/destroy-branch-qa.yaml
CHANGELOG.md
task-definition.json

This adds an action to add a service to the QA ECS cluster that deploys the current branch on a temporary basis. This has a bare IP address that is added as a comment to this PR. This can be used to QA specific changes to the front and back ends.

SFR-1057 Add Temporary deployment Action

---

.github/workflows/destroy-branch-qa.yaml
CHANGELOG.md
api/blueprints/drbEdition.py
api/blueprints/drbLink.py
api/blueprints/drbOPDS2.py
api/blueprints/drbSearch.py
api/blueprints/drbUtils.py
api/blueprints/drbWork.py
api/db.py
tests/unit/test_api_db.py

This refactors the API db connection/session structure so that sessions are closed after queries. This resolves a bug in the API that is returning a `TimeoutError` for too many connections.

NOREF Close sessions after queries

---

.github/workflows/build-branch-qa.yaml
CHANGELOG.md
task-definition.json

In the temporary environments the front-end application was unable to reach the API due to a misconfigured environment variable. This corrects the issue and ensures that multiple QA environments can be present at the same time.

HOTFIX Update Temporary QA API URL

---

.github/workflows/build-branch-qa.yaml
README.md

This makes two fixes to the temp URL provided for the QA environment(s). This is now the public IP address for the service, so that users do not need to be on the vpn, and it updates with pushes, to ensure accuracy if the IP address changes

Hotfix update temp url

---

CHANGELOG.md
managers/oclcClassify.py
mappings/json.py
mappings/met.py
processes/__init__.py
processes/core.py
processes/met.py
processes/oclcClassify.py
tests/unit/test_core_process.py
tests/unit/test_json_mapping.py
tests/unit/test_met_mapping.py
tests/unit/test_met_process.py
tests/unit/test_oclcClassify_manager.py
tests/unit/test_oclcClassify_process.py

This adds a new process for ingesting MET Publications into the DRB collection. These publications are available as PDF files via the MET's CMS (which is powered by OCLC's Contentdm product).
The data is available as JSON documents, so a new mapping format has been created to handle the records. At the moment this mapping is fairly bare-bones and only supports strings and arrays as values in tho documents. For full support the ability to parse nested objects in the document will need to be added in the future.
The MET API does not allow for sorting/filtering on modified dates for their records, though the field is present. In order to provide regular updates then the full collection (roughly 3,000 records) must be iterated with old/outdated records skipped.
This addition represents the …

SFR-955 Create MET Process

---

CHANGELOG.md
processes/sfrCluster.py
tests/unit/test_sfrCluster_process.py

In rare instances a record without a title can be created. When these are encountered an exception is raised and the record skipped from the clustering process

HOTFIX Skip records without titles when clustering

---

CHANGELOG.md
api/elastic.py
api/utils.py
tests/unit/test_api_es.py
tests/unit/test_api_utils.py

A bug was present in the publication date sorting process as the path for the filter was incorrect. This corrects the path to ensure that the nested `editions.publication_date` field is properly used to sort records

SFR-1075 Fix year sorting

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

To properly parse complex queries they must be split on commas. However this can cause issues when a comma is in a quoted phrase. This has two unintended consequences:
- The query is split when the user almost certainly wanted that search executed as a phrase
- The splitting results in a syntax error because it results in open quotation marks that cannot be resolved by ElasticSearch
This resolves these issues by implementing a regex to split the query string that takes quotation marks into account. Through this the semantic meaning of the quotes is preserved and the query is only split on intended commas.

SFR-1082 Don't split queries on commas within quotation marks

---

config/production.yaml

This adds the local environment variable file for the production environment. Because this only contains non-sensitive values mostly are the same as in QA, only they contact different services. Those sensitive values are controlled in the AWS Parameter Store and can be updated as necessary there.

Sfr 1099 add production variables

---

CHANGELOG.md
managers/s3.py
processes/gutenberg.py
tests/unit/test_gutenberg_process.py
tests/unit/test_s3_manager.py

This resolves two issues with ePub files on ingest (when they are stored in s3):
* When ePub paths contain periods (as with DOI identifiers) the ePub manager failed to properly parse the location. This resulted in ePub files that could be loaded in the webreader. This updates the parser to handle multiple periods and resolve the issue.
* A regression affecting Gutenberg files caused their XML entrypoint files to be set as `content.xml` when the file should be `container.xml` which was fixed with a simple substitution.

SFR-1115 ePub Storage Bugfixes

---

CHANGELOG.md
processes/gutenberg.py
tests/unit/test_gutenberg_process.py

In very rare cases a `metadata.yml` file can be generated for a Gutenberg work without a cover reference. This simply handles the error raised in that case, logs the event and continues. While we would like covers for all works, we do not consider a missing cover a reason to block ingest of a record.

HOTFIX Handle edge case error

---

CHANGELOG.md
mappings/hathitrust.py
tests/unit/test_hathitrust_mapping.py

Google disallows downloads for their digitized volumes in HathiTrust. These were being made available and needed to be removed. This institutes a simple block to enforce this.

HOTFIX Block downloads for Google digitized books

---

CHANGELOG.md
api/blueprints/drbSearch.py
api/elastic.py
api/utils.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py

This removes links that do not match the currently configured format filter (and still return all links if no filter is set). This ensures that users see the expected results when they select a filter.
This is fairly simply due to the fact that the filter already removes any `Item` records that do not contain a valid link. So this must simply remove any other links on the records that are included.

SFR-1098 Format Link Filtering

---

managers/db.py
managers/sfrRecord.py
processes/sfrCluster.py
tests/unit/test_sfrCluster_process.py
tests/unit/test_sfrRecord_manager.py

The current method for updating work records makes a faulty assumption about how the sqlalchemy `merge` method works. This is simply replaced with a different approach that deletes pre-existing records that are updated and assigns the oldest relevant created date to the newly created work record. This better reflects the process and should be faster.

HOTFIX Resolve work merging method bug

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

A regression in the ElasticSearch query class prevented set filters from being applied to aggregation buckets. This meant that the buckets displayed inaccurate counts of works returned in the search.
This was due to a misnamed variable, correcting that issue resolves the bug

SFR-1121 Fix Language Filter Bug

---

managers/sfrRecord.py

The hotfix to improve the work updating process introduced a regression that blocks the processing of new works. This updates the method to handle both.

HOTFIX Handle non-matched works

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

In anticipation of the new webreader, many files (primarily from Project MUSE and DOAB) have been stored as Webpub manifests, which can make PDF files readable through several means. However, this reader is not yet available, meaning that these files can throw errors. This blocks them from being included in API responses until the reader is ready.
When it is, a single line (and corresponding test) will need to be removed to re-enable this functionality

SFR-1097 Remove webpub pdfs

---

managers/sfrRecord.py
processes/sfrCluster.py
tests/unit/test_sfrCluster_process.py
tests/unit/test_sfrRecord_manager.py

Previous iterations of the matching and merging of work records after they have been clustered relied on a number of tricks. This simplifies the process such that new works simply overwrite older works, copying over the creation date for continuity.
This fix updates the deletion process to ensure that records are properly deleted and that identifiers are not removed mistakenly during indexing

HOTFIX Simplify Work persistence and merging

---

.github/workflows/build-production.yaml

When a release is cut from a tag this action is triggered and deploys an updated version of the code to the production ECS stack.

NOREF Add Github Action for production deployment

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

This corrects two bugs with the edition detail view:
- In the context of an edition detail the `showAll` filter was not being passed to the proper method. Asa result the corresponding function on the front end did not update the detail page. This passes the variable to the correct function and applies the logic when iterating through the component records of an edition.
- Some `record` entries have `has_part` items that are not present as links. These need to be filtered out from responses. This was already being detected but not properly filtered from the final array. This simply enforces a `None` check to make this method behave properly.

SFR-1113 & SFR-1124 Edition Detail Fixes

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

The logic for applying the `showAll` logic in edition detail was reversed, due to a backwards test case. This is resolved in this commit

HOTFIX showall boolean logic

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

This fix consistently sorts editions within work detail pages. This ensures that users have a consistent and logical experience when looking at work details.

SFR-1133 Order Editions on Work Detail Page

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

The currently implemented blocklist was not properly filtering roles during author searches. This resulted in unexpected results for author searches. Because it is difficult to predict what role will be used in metadata records, this block list is replaced with an allowlist that explicitly defines the roles that are considered valid for an author search.
This is more restrictive but should be consistent in the long term regarding what is matched for such searches. The list can be extended if necessary.

SFR-1094 Author Role Update

---

CHANGELOG.md
api/app.py
api/blueprints/drbSearch.py
api/elastic.py
managers/elasticsearch.py
processes/api.py
tests/unit/test_api_es.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_es_manager.py

This improves the ElasticSearch client by implementing the default connection style as specified by the high-level `elasticsearch-dsl` package. This should give us more confidence that connections to the ES cluster are being managed in a logical way and will not cause any unanticipated errors.

SFR-1156 Simplify ES Client

---

api/blueprints/drbOPDS2.py
api/blueprints/drbUtils.py
tests/unit/test_api_opds_blueprint.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils_blueprint.py

Two flask blueprints still contain references to a configuration variable that is no longer present with the new ElasticSearch client connection. This simply removes those references.

SFR-1156 Remove ES_CLIENT for utils and OPDS2

---

CHANGELOG.md
managers/sfrRecord.py
tests/unit/test_sfrRecord_manager.py

In the current clustering step records with LCNAF/VIAF numbers are being omitted from the edition-level clustering step. This is because they contain no edition-level metadata. This adds an additional step to silo these records and pull out relevant work-level metadata, most importantly the VIAF and LCNAF numbers for authors.

NOREF Fix VIAF/LCNAF parsing

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

Previously query strings were split on commas (except for those contained in quotation marks). But this can still have unintended behavior when commas are part of a query. This resolves the issue by instead only splitting queries when a query term is present (e.g. `title:` or `subject:`). If a non-prefixed query is present or is first in a query string that is properly parsed. This should not impact any queries made by any existing applications and should only marginally impact any queries as most (if not all) users will expect this behavior.

SFR-1123 Author Paren Search

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

This corrects a bug that results in a `500` error when no documents are matched in ElasticSearch

HOTFIX Empty result set

---

CHANGELOG.md
api/blueprints/drbUtils.py
api/elastic.py
task-definition.json
tests/unit/test_api_es.py
tests/unit/test_api_utils_blueprint.py

This implements a simple fix for a regression that is currently blocking the use of Advanced Search in DRB. The root cause is a missing redis client in a Flask endpoint.
In a related update this also changes how results are sorted to realize more pertinent results for users (and corrects an issue that was causing some errors to show up).

NOREF Fix Advanced Search

---

CHANGELOG.md
config/development.yaml
config/example.yaml
config/production.yaml
config/qa.yaml
managers/parsers/degruyterParser.py
managers/parsers/frontierParser.py
managers/parsers/openEditionParser.py
managers/parsers/springerParser.py
processes/gutenberg.py
processes/s3Files.py
tests/helper.py
tests/unit/test_gutenberg_process.py
tests/unit/test_parser_degruyter.py
tests/unit/test_parser_frontier.py
tests/unit/test_parser_openedition.py
tests/unit/test_parser_springer.py
tests/unit/test_sfrFile_process.py

This adds a step to the ingest process for ePub files (from DOAB and Project Gutenberg at present). In order to be compatible with the new reader ePub files will have to be made available through a Readium Webpub manifest. These manifests can be generated from an ePub's `container.xml` file using the epub-to-webpub tool that Kristo has created.
This tool is loaded as a 3rd-party service, which returns a JSON blob as a response and which can be stored in s3, alongside the content of the ePub file.
This generates an additional way of accessing these files and creates a new link in the DCDW database with a media type of `application/webpub+json` which can be read by client applications. At present the other means of accessing the ePub files are still present so it is up to client …

SFR-1065 Implement Webpub Conversion

---

managers/parsers/defaultParser.py
tests/unit/test_parser_default.py

In the previous merge from this working branch the default DOAB parser was not updated to generate new webpub URLs. This adds this URL to that method.

SFR-1065 Update default DOAB parser

---

CHANGELOG.md
managers/elasticsearch.py
managers/sfrElasticRecord.py
managers/sfrRecord.py
processes/oclcCatalog.py
tests/unit/test_oclcCatalog_process.py
tests/unit/test_sfrElastic_manager.py
tests/unit/test_sfrRecord_manager.py

This implements two minor but important stability improvements. First, it extends the wait period in the catalog process. Delays in the classification process are causing this process to exit early, extending the wait process should improve this, though it may need to be further extended. Second, timeout errors are handled in the cataloging process so that the saving of elastic records is retried. This should help the process run to completion in a consistent manner.

Noref stability improvements

---

CHANGELOG.md
processes/covers.py
processes/sfrCluster.py
tests/unit/test_cover_process.py
tests/unit/test_sfrCluster_process.py

This makes two improvements to the ingest process:
- The Cluster process is restricted to reading non-OCLC records which should improve overall execution time as those records should always be associated with a different source
- The max execution time of the cover process is set to 12 hours so that API rate limits have time to reset between executions

NOREF Improve Cluster and Cover stability

---

CHANGELOG.md
api/blueprints/drbUtils.py
swagger.v4.json
tests/unit/test_api_utils_blueprint.py

This adds a new endpoint that proxies requests for resources. It is intended for use with the webreader when that application has difficulty loading resources. At present it has a CORS header setting to only accept requests from `.nypl.org` addresses. This is a (probably over-cautious) security setting but shouldn't prove too difficult to work with in testing scenarios

SFR-1221 Add proxy endpoint

---

api/blueprints/drbUtils.py
tests/unit/test_api_utils_blueprint.py

To check for redirects in proxy requests HEAD requests are made. In some instances these requests can cause issues, so this updates the process to be slightly more robust

SFR-1221 Improve HEAD request method

---

api/blueprints/drbUtils.py
config/development.yaml
config/example.yaml
config/production.yaml
config/qa.yaml
task-definition.json

To increase the testability of the proxy endpoint (especially when testing other components of the DRB application) this makes the source of CORS requests to the proxy endpoint configurable via environment variable. This should make interacting with the proxy to test the development of othe components much easier

NOREF Make Proxy CORS configuration configurable

---

CHANGELOG.md
config/development.yaml
config/example.yaml
config/production.yaml
config/qa.yaml
managers/parsers/abstractParser.py
managers/webpubManifest.py
processes/met.py
processes/muse.py
tests/helper.py
tests/unit/test_met_process.py
tests/unit/test_muse_process.py
tests/unit/test_parser_abstract.py
tests/unit/test_webpub_manifest.py

In order to facilitate the use of PDF files in Webpub Manifests, web reader clients need a method of determining the contents of a manifest. The established way of doing so is to use the `conformsTo` option in the metadata block. This implements this for PDF manifests only (as ePub manifests are assumed to be the default in the current web reader)
A PDF profile has been defined so the only udpate here is to include the relevant URI for PDF manifests as they are generated. This is configurable via an environment variable.

SFR-1245 Add Conforms to for PDFs

---

CHANGELOG.md
alembic.ini
main.py
migrations/env.py
migrations/script.py.mako
migrations/versions/fabf5e5c3109_add_collections_table.py
model/postgres/collection.py
processes/__init__.py
processes/migration.py
requirements.txt
tests/unit/test_main_process.py
tests/unit/test_migration_process.py

This adds a new table to the postgres model to hold collections (and associated editions). This migration is necessary to support the collections feature to be shown as a POC for further development.
To imploment this work we have added the alembic module for managing migrations. This module can be invoked via the normal process via the CLI or a container. Arbitrary arguments can be passed to upgrade/downgrade the database model as needed and as a result all future database updates will be versioned.

SFR-1068 Collections db model

---

CHANGELOG.md
api/blueprints/drbCollection.py
api/db.py
swagger.v4.json
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py

This adds an endpoint that lists all collections in the database. It is paged and defaults to a page size of 10. Within the collection of collections, each collection displays the first 5 works within it.

SFR-1247 Add collection list endpoint

---

CHANGELOG.md
api/blueprints/drbCollection.py
api/blueprints/drbUtils.py
api/db.py
api/opdsUtils.py
api/utils.py
migrations/versions/975e451df332_add_user_table_for_basic_auth.py
model/__init__.py
model/postgres/user.py
swagger.v4.json
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py
tests/unit/test_api_utils.py
tests/unit/test_api_utils_blueprint.py

This implements a simpler, DRB-specific authentication system for interacting with collections. This enables DRB to distribute credentials on an as-needed basis and remove a dependency on the NYPL ISSO service. For the purposes of the simple collection POC this is more than sufficient and ensures that creation and protection are limited, and that users can only delete resources that they control

SFR-1068 Update auth method

---

CHANGELOG.md
swagger.v4.json

Previously swagger was explicitly setting the scheme to be used by endpoints. Since this causes an error when loading in a different scheme (as would happen by default) this is removed in favor of using the currently deployed scheme. This works because the swagger documentation and API endpoints will always be deployed in the same manner.

NOREF Update swagger to default theme

---

CHANGELOG.md
api/app.py
api/blueprints/drbEdition.py
api/blueprints/drbSearch.py
api/blueprints/drbWork.py
api/utils.py
config/development.yaml
config/example.yaml
config/production.yaml
config/qa.yaml
mappings/nypl.py
mappings/oclcCatalog.py
swagger.v4.json
tests/unit/test_api_edition_blueprint.py
tests/unit/test_api_es.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py
tests/unit/test_api_work_blueprint.py
tests/unit/test_nypl_mapping.py

This adds a new parameter to the search, work and edition endpoints that controls what `media_types` are returned for links. This allows the API to return results that are compatible with multiple readers, and importantly allows DRB to deploy new readors on the front-end with zero downtime

NOREF Add readerVersion parameter

---

CHANGELOG.md
api/blueprints/drbUtils.py
processes/sfrCluster.py
tests/unit/test_api_utils_blueprint.py
tests/unit/test_sfrCluster_process.py

This implements a simple fix for the proxy endpoint that handles relative redirects from source files. It resolves these using the extracted scheme and netloc of the original url, which must contain these values.
In addition this tweaks the settings for the clustering process to produce more accurate work records.

HOTFIX Improve Record Handling for new reader

---

CHANGELOG.md
managers/s3.py
tests/unit/test_s3_manager.py

When ingesting epub files and cover images to s3 the aws process assigns a default content type of `binary/octet-stream`. Previously this was not a problem but the new reader checks the types of files it loads. The fix for this is a simple implementation using pythons core `mimetypes` module that provides accurate string identifiers. It does not appear that a more advanced implementation of this is necessary.

NOREF Add content_type detection to the s3 process

---

CHANGELOG.md
mappings/doab.py
mappings/hathitrust.py
mappings/met.py
mappings/muse.py
mappings/nypl.py
mappings/oclcCatalog.py
tests/unit/test_hathitrust_mapping.py

To make it easier for the DRB front end (and other applications) to identify "embedable" HTML book links this adds an explicit `embed: true` flag on these link objects. Previously it was assumed that this could be infered but it is more reliable and transparent to provide a positive flag for this functionality

NOREF Add explicit embed flag

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

This branches sets up the internal query structure needed to return search highlighting for any/all queries made in ElasticSearch. A highlighting clause is added to all searches on all fields applicable for the current search. The following settings are implemented:
- Highlighted snippets are scored and returned in order of relevance
- A maximum of 10 snippets are returned per field searched
- No HTML tags are added to the snippets to provide highlighting, as they are too application-specific
This addition is not yet visible in the API, this is only the internal application. Any testing of this code should ensure that queries still function as they did previously, and that no errors are encountered when querying.

SFR-1303 Add Highlighting Clause

---

CHANGELOG.md
api/blueprints/drbUtils.py
config/development.yaml
task-definition.json
tests/unit/test_api_utils_blueprint.py

This extends some settings for the proxy endpoint, allowing it to accept `OPTION` requests, which are necessary for the CORS preflight checks to pass

NOREF Improve proxy endpoint

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_es.py

An issue when filtering with formats was due to a conflict with how webpub manifests must be handled. This removes that format from basic filtering and adds it back to criteria when necessary. This simplifies the process and ensures that the filters work conceptually as they would be expected to.

NOREF improve format filtering

---

.github/workflows/build-production.yaml
CHANGELOG.md
api/utils.py
managers/parsers/mdpiParser.py
tests/unit/test_api_utils.py

To ensure that the API stays stable and continues to serve expected responses, this adds a few minor updates to the deployment process. None of these make substantive changes to the API, but ensure that deployments are more stable and help with the transition to the new web reader.

NOREF EDD Deployment Updates

---

CHANGELOG.md
api/blueprints/drbOPDS2.py
api/blueprints/drbSearch.py
api/utils.py
tests/unit/test_api_opds_blueprint.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py

This adds the highlighted fields from ElasticSearch to the DRB API response for both the default DRB API format and the OPDS2 feed. This provides information to consuming applications about what strings, in what fields, were matched against.
This is returned in a new `_meta` object in both APIs, an object is designed to be extensible and contain future metadata about DRB records in the future (prior to this all metadata pertained to the works being described by the DRB records).

SFR-1304 Add Highlighting to API

---

CHANGELOG.md
api/blueprints/drbUtils.py
tests/unit/test_api_utils_blueprint.py

In rare cases (from a subset of publishers) `302` redirects may exhibit odd behavior that prevents them from being handled in a standard way. This inserts a fallback that relies on the `requests` module parsing of the redirect. While generally this can have issues, these edge case redirects are accurately handled by the module (as it more closely represents a browser environment).

SFR-1387 Improve proxy redirects

---

config/qa.yaml

At present "test" deployments of the ePub-to-Webpub application on Vercel fail because they rely on the DRB API QA instance to proxy materials. This is because the CORS headers are set to be too restrictive. This should relax that requirement somewhat to enable these requests.

NOREF Fix QA CORS Vercel Integration

---

README.md

This update improves the README to better reflect the current state of the repo. Most importantly it removes any references to Kubernetes, which is currently not being used.
It also attempts to more clearly define dependencies of the project and the steps necessary to set up a local development version of the project.

NOREF Update README

---

.github/workflows/tests-unit.yaml
.gitignore
CHANGELOG.md
api/blueprints/drbOPDS2.py
managers/elasticsearch.py
requirements.txt
tests/unit/test_api_opds_blueprint.py
tests/unit/test_es_manager.py

DRB was recently updated to use the latest ElasticSearch 8.x release version, which necessitated several updates of internal logic. A few aspects were missed or not fully understood in this process:
- The OPDS2 client was not updated to take into account changes to the `meta` and `total` objects in the ES response
- Timeouts were not properly applied to the ElasticSearch client used for bulk indexing
In addition to this a few changes were made to clean up some dangling logs and update tests

HOTFIX ElasticSearch 8 Fixes

---

CHANGELOG.md
managers/elasticsearch.py
tests/unit/test_es_manager.py

Due to an issue in the ElasticSearch 8.x python client, we cannot control the timeout values for bulk operations in ES. This is an occasional issue that crops up with large batches of records.
This fix adds a split and retry functionality for batches, catching `ConnectionTimeout` errors, splitting the offending batch in half and retrying each recursively.

SFR-1456 Add ES Retry Functionality

---

CHANGELOG.md
api/blueprints/drbWork.py
api/utils.py
tests/unit/test_api_utils.py

I'm not sure if I should insert a space between the d and T, so it's clearer to see the date properly in the API Response or if it should stay this way since it needs to be there no space for the regression tests.

Sfr 1469 date in api response

---

model/postgres/record.py
tests/unit/test_model_record.py

This is a minor fix to an edge case where no edition statement (`has_version`) in the `Record` table model is present

HOTFIX Add has_version None handler

---

config/qa.yaml

This updates our CORS configuration to accept requests from a new format of URLs from the now Vercel-hosted QA environment

HOTFIX Update Vercel CORS string

---

CHANGELOG.md
processes/doab.py
tests/unit/test_doab_process.py

The method to import individual DOAB records (used for testing and dev purposes) had broken due to a change in DOAB's OAI-PMH feed. This updates the method to accurately extract the correct XML object that can be understood by the DOAB mapping.

NOREF Fix DOAB single record import

---

CHANGELOG.md
api/utils.py

In previous versions of the API, unexpected `media_type`s caused a `500` error. This allows for handling of these values, and extends the current lookup dictionary to anticipate some upcoming improvements

NOREF Fix media_type handling

---

CHANGELOG.md
scripts/__init__.py
scripts/updateESEditionFormats.py

This script finds all work/edition records that have a resolvable link pointing to an NYPL resource. If that resource is a link to a catalog record (not to an EDD option), the `mediaType` of that link is updated to `application/html+catalog` which prevents these links from being picked up as readable.

Sfr 1498 update es catalog links

---

CHANGELOG.md
api/elastic.py
api/utils.py
managers/sfrElasticRecord.py
scripts/__init__.py
scripts/govDocES.py
tests/unit/test_sfrElastic_manager.py

I updated the sfrElasticRecord module to utilize the measurements field of editions instead of works when calling the addGovDocStatus() method and made a new script to update old government document works in ES with a True boolean value in their is_government_document fields.

Sfr 1506 gov doc in es

---

CHANGELOG.md
api/elastic.py
api/utils.py

To add the government document filters to the backend, I decided to first add two new QUERY_TERMS to represent the "onlyGovDoc" and "noGovDoc" filters. Then, I'm currently attempting to update the "createFilterClausesAndAggregations()" method in the Elastic API to add these two filters, but I'm struggling to understand how to format my queries for these filters especially since the measurements field of edition is a jsonb object. This object has two terms I need to search for which are the type and value that should be "government_document" as the type and "0" or "1" as the value. The two conditionals I made in this method are commented out for right now since I'm still thinking how the queries should look for both filters.

Added two filters for govDoc and noGovDoc

---

CHANGELOG.md
api/blueprints/drbCollection.py
api/blueprints/drbSearch.py

This removes trailing slashes from two API endpoints -- `search` and `collection`. This misconfiguration was causing issues with the Swagger documentation, resulting in false errors when interacting with the API.
The only effect of this change should be to resolve those errors, any other interaction with the API should result in a `308` redirect, which is invisible in other use cases.

HOTFIX Remove trailing slashes from API Endpoints

---

CHANGELOG.md
processes/__init__.py
processes/dbMaintenance.py
processes/ingestReport.py
tests/unit/test_dbMaintenance_process.py
tests/unit/test_ingestReport_process.py

This addresses an issue raised by the project/product teams to fix broken reporting of daily ingest volume. There are two related fixes for this issue in this PR:
1. The immediate issue is resolved by updating the analytics queries. an ineffecient strategy was being used to create date-based queries. This has been removed and replaced with a more standard query structure.
2. This is supported by the addition of a database maintenance process. Without this standard process database table can grow slow and harder to query. This provides a tool that can be used to ensure that the database is regularly pruned of unused rows.
Overall this should restore intended functionality to the database and ensure that similar situations do not occur in the future. It should also provide a safeguard …

SFR-153 Ingest Report Fix

---

CHANGELOG.md
managers/sfrRecord.py
requirements.txt

I updated the search score to 0.85 instead of 0.9 and specified the version number of the `python-levenshtein` dependency in the requirements file to be 0.20.4.

Updated search score in agent parser method

---

CHANGELOG.md
api/elastic.py
api/utils.py
tests/unit/test_api_es.py

With this PR I added a new conditional for the `generateSearchQuery` method to include identifier as a field and made a `identifierQuery` method to account for that. In addition, instead of adding another conditional for an authority field, I decided to update the existing viaf and lcnaf conditional since they seemingly utilize an authorityQuery method which is similar to what we want for when one searches for a specific authority and the identifier afterwards. What are your thoughts on doing this rather than creating a separate conditional and new authorityQuery method? Also, I only included isbn and lccn as new authorities for right now, since I'm not aware and don't have access to the ES QA database to check all the types of authorities that exist for each record. Could you assist me …

Updated ES API generateSearchQuery method

---

CHANGELOG.md
api/elastic.py
scripts/deleteElasticRecords.py
tests/unit/test_api_es.py

I changed the identifier queries to resemble the author queries since both of them utilize nested fields when searching. Due to this change, I adjusted the unit tests as well.

SFR-1509v2: Updated identifier query for nested search

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

In this branch, I decided to replace the colon and space characters when splitting the identifier query into just a pipe character which should help fix the tests in QA concerning the search results of "identifier type: value" returning nothing. However, this fix doesn't attempt to fix the identifier query when a doab identifier is given, so I think it best to create a separate bug ticket to fix this edge case at a later date.

SFR-1509_v3: Replacing colon with pipe character in identifier query

---

CHANGELOG.md
api/blueprints/drbCollection.py
scriptRunner.py
scripts/deleteElasticRecords.py
scripts/extractAllEditions.py
scripts/govDocES.py
scripts/updateESEditionFormats.py
scripts/updateLinksCatalog.py
scripts/updateOldInTechOpenLinks.py
scripts/updateRecordsCatalogLink.py

This PR focuses on updating the collectionFetch endpoint with the Read Online link that was previously not visible such as this [https://digital-research-books-beta.nypl.org/read/543649](url). I'm not sure if the rel, type, and id in the url I typed are the correct ones, but the format is similar to the other links in the array. Sean gave an example of a collection with no Read Online link on Jira under the comments of the SFR-1543 ticket as well. Also, I removed the `loadEnvFile` from all the modules in the `scripts` directory since the `scriptrunner.py` module has it already.

SFR-1543: Adding Read Online Link to Collections

---

CHANGELOG.md
api/elastic.py
tests/unit/test_api_es.py

In this PR, I replaced the escapedQuery in the `identifierQuery` and `authorityQuery` method with the original query, so special characters aren't escaped when searching for specific identifiers like DOAB or DOI. Also, I removed the backslash when splitting the `authIdent` list by the pipe character since the query is no longer being escaped.

SFR-1578: Updated identifier search for escaped characters

---

CHANGELOG.md
swagger.v4.json

Jackie informed me that `perPage` and `sortBy` parameters are missing from the /collection/{uuid} GET request endpoint since they’ll be needed when retrieving data from the Collections page on the frontend, so I added the parameters in the swagger file and they should appear in the QA apidocs site (https://drb-api-qa.nypl.org/apidocs/#/) when this branch is merged into main.

HOTFIX: Added new parameters to collection/uuid endpoint

---

CHANGELOG.md
api/blueprints/drbEdition.py
api/blueprints/drbWork.py
api/utils.py
swagger.v4.json
tests/unit/test_api_edition_blueprint.py
tests/unit/test_api_utils.py
tests/unit/test_api_work_blueprint.py

In this PR, I updated APIUtils with a new checkEditionInCollection method for the work and edition API responses which adds  the metadata objects of the collections these works/editions are part of within an array. I also adjusted the tests and fixed a small typo in the swagger document. Some feedback on simplifying the queries or conditionals would be helpful.

SFR-1590_inCollection Property in Work and Edition API Responses

---

CHANGELOG.md
main.py
processes/oclcClassify.py

I *believe* this is the missing piece for covering our non web processes for full instrumentation.  Basically, we just need to register an app and pass that to the BackgroundTask context manager to get the newrelic agent to fully instrument and forward logs from these tasks.
To test this, I performed the Docker based newrelic agent installation on my machine, ran the ClassifyProcess locally, and observed logs and metrics in the 'DRB ETL Pipeline (DEV)' app in newrelic APM.
Using this, looks like we don't need to individually decorate methods being called in the task.  I only removed the decorators from the ClassifyProcess for now so that we can first verify this in prod.
https://jira.nypl.org/browse/SFR-1603

Register background task apps for new relic

---

api/blueprints/drbSearch.py
api/utils.py
tests/unit/test_api_search_blueprint.py
tests/unit/test_api_utils.py

Looks like we weren't passing the client object, but failing with a default of `None`. Since the dbClient appears to be required for this to run, remove the default and pass it in.  Might make sense to require keyword args on some of these methods at some point.

fix: Pass DBClient to work formatter in search

---

CHANGELOG.md
processes/core.py
processes/covers.py
processes/dbMaintenance.py
processes/doab.py
processes/gutenberg.py
processes/hathiTrust.py
processes/ingestReport.py
processes/met.py
processes/muse.py
processes/nypl.py
processes/oclcCatalog.py
processes/s3Files.py
processes/sfrCluster.py

Verified the new intrumentation approach works in QA, so we don't need to decorate all these methods anymore
https://jira.nypl.org/browse/SFR-1603

Remove remaining background_task decorators

---

.github/workflows/tests-regression.yaml
.github/workflows/tests-unit.yaml
CHANGELOG.md

Noticed we're still running 3.8 for our test workflows while running 3.9 in prod

fix: Bump python version for CI tests

---

api/utils.py

This change is due to the collection uuid being needed to link to the collections page on the frontend.

HOTFIX: Changed id to uuid for inCollection metadata object

---

CHANGELOG.md
migrations/versions/e46b30dd3ff5_automatic_collections.py

To support defining 'automatic' collections, define a new 'automatic collection definition' defining search terms to define an automatic collection. These terms will essentially mirror what we already use to hit ES when searching for works. We'll probably special case the example of the 'most recent' collection to just hit the DB, but otherwise we'll dynamically load the search terms into an ES query.
Otherwise, these automatic collections will simply be collections with a new collection 'type' of 'automatic' (defaulting all existing collections to 'static'), so we can reuse all the metadata fields on the existing collection.
Some specific things I have questions / would like feedback around:
- Reusing the collection table for storing collection metadata (as opposed to creating a new …

Add 'automatic' collections DB entities

---

CHANGELOG.md
api/automaticCollectionUtils.py
api/blueprints/drbCollection.py
api/db.py
model/__init__.py
model/postgres/collection.py
scripts/addMostRecentAutomaticCollection.py
tests/unit/test_api_automatic_collection_utils.py
tests/unit/test_api_collection_blueprint.py

https://jira.nypl.org/browse/SFR-1584
As a first step, add the new models and implement the logic to fetch
editions for any collections not requiring text search. In these cases,
such as with the main example of a 'Most Recent' collection, we can just
hit the DB. This also includes a script to generate the 'Most Recent'
collection.
In a later diff, I'll implement handling of all the text search fields
that we are currenly ignoring.
Note, this branch is based on the migration branch https://github.com/NYPL/drb-etl-pipeline/pull/224 so this PR is currently against the branch on that PR. Once the migration goes in, I'll reset the base on this one to main before merging!

Implement non search based automatic collection 

---

CHANGELOG.md
api/blueprints/drbCollection.py
config/sample-compose.yaml
swagger.v4.json
tests/unit/test_api_collection_blueprint.py

In this PR, I have created a new endpoint called `collectionUpdate` that for right now is focused on having engineers on the backend able to replace a collection that's currently in the database with a new collection that the user creates. I'm currently working on tests and updating the swagger file to reflect these changes.

SFR-1582:Added new collectionUpdate endpoint

---

swagger.v4.json

Added a closing curly bracket to close the collectionUpdate endpoint which caused errors on the apidocs QA site when the endpoint wasn't properly closed.

HOTFIX: Closed out endpoint with closing curly bracket

---

api/blueprints/drbCollection.py
api/db.py
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py

Due to the recent database migration for automated collections, the createCollection endpoint returned a 500 integrity error due to the createCollection method in the dbClient not specifying a 'type' as a parameter which is now a column in the collections table. Now, I have defaulted the 'type' in the endpoint and dbClient method to be static at all times to resolve this issue.

HOTFIX-Added type parameter to dbClient.createCollection

---

CHANGELOG.md
api/automaticCollectionUtils.py
api/blueprints/drbCollection.py
api/db.py
tests/unit/test_api_automatic_collection_utils.py
tests/unit/test_api_collection_blueprint.py

If we encounter an automatic collection with search parameters, build
up an elastic search query and return the results.
https://jira.nypl.org/browse/SFR-1584

Add logic for search based collection 

---

CHANGELOG.md
api/blueprints/drbCollection.py
swagger.v4.json
tests/unit/test_api_collection_blueprint.py

This endpoint will be tailored to have the user choose which metadata values to update through request parameters. In later commits, I will update the swagger file and unit tests in consideration of this new endpoint.

SFR-1614_New collection endpoint to selectively update metadata

---

CHANGELOG.md
api/blueprints/drbCollection.py
api/opds2/link.py
api/opds2/publication.py
tests/unit/test_api_collection_blueprint.py
tests/unit/test_opds_publication.py

In this PR, I added an identifier value to the publication links for each edition to categorize the links as readable, downloadable, requestable, catalog, and other in the fetchCollection API response.

SFR-1636: Make collection links identifiable

---

CHANGELOG.md
api/automaticCollectionUtils.py
api/blueprints/drbCollection.py
api/db.py
model/postgres/collection.py
swagger.v4.json
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py

https://jira.nypl.org/browse/SFR-1611
Accept some new data in the request body that indicates the user wants
to create an automatic collection. Do some validation and then do the
creation.
Note, I had to augment the sqlalchemy models to allow for creating both
entities in a single transaction.

Support automatic collections in POST /collection 

---

CHANGELOG.md
config/production.yaml
config/qa.yaml
managers/oclcClassify.py
tests/unit/test_oclcClassify_manager.py

With this PR, I updated the OCLC Classify API with an updated root url, adding a header to the query for the classification process, and updated the API keys for the qa and production config files.

SFR-1633: Updated OCLC Classify API

---

tests/helper.py

This hotfix adds a mock OCLC Classify API Key to the environment variables of the unit tests

Hotfix-Added Mock OCLC Classify Key

---

api/blueprints/drbCollection.py
api/db.py
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py

This hotfix allows any authenticated user to delete a collection even if they're not the owners of that collection.

HOTFIX_DeleteCollectionAuthentication

---

scripts/deleteDuplicateAgents.py

This PR addresses an issue that came up with running the original version of this script where any author/contributor JSONB object that had more than 2 author/contributor names would have the next element after the first one delete itself because the `nextIndex` would stay at index of 1 instead of always being one more than than the `currIndex`. The change to the for loop should fix this issue and logging was added for testing and dry run attempts. Lastly, the edition for loop is outside of the work for loop because the query originally would only find editions that were in works with multiple authors/contributors instead of any edition with multiple contributors which broadens the query.

SFR-1647v2_DeleteDuplicateAuthors&Contributors

---

.github/workflows/tests-regression.yaml
.github/workflows/tests-unit.yaml
CHANGELOG.md
requirements.txt

A change to pip's behavior caused the fasttext install to not dynamically install pybind11 for us. By explicitly adding wheel to pip, we can revert to the old behavior for now.  Eventually, fasttext will need to implement a fix on their end, but for now this works.
See:
- https://github.com/pypa/pip/issues/8559 for the deprecation
- https://github.com/pypa/pip/issues/11978#issuecomment-1513360038 for example of the workaround

fix: Install `wheel` with pip

---

api/utils.py

This hotfix adds ISAC to the Source Priority dictionary which allows ISAC works to be searched for in the API and on the frontend.

Add ISAC to Source Priority dictionary

---

CHANGELOG.md
api/blueprints/drbCollection.py
api/db.py
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_db.py

See each commit, but both commits are essentially to fix issues with running queries in loops. The first refactors a method call to accept `collection` objects instead of uuids to avoid an extra roundtrip to the DB.
The second one eager loads collection relationships to again avoid roundtrips in the DB in some loops

Fix DB perf issues

---

CHANGELOG.md
processes/developmentSetup.py
tests/unit/test_developmentSetup_process.py

Noticed when spinning up a new environment that these SQL statements fail because our version of sqlalchemy doesn't accept raw strings, but rather requires wrapping them in executable text objects.
I also switched over to f strings while I was at it

Wrap DDL in dev setup process in `sqlalchemy.text`

---

CHANGELOG.md
scripts/__init__.py
scripts/updatePubLocationAndLinks.py

This branch intends to fix the publisher location of Chicago ISAC records from `Chicago|publisherLocation` to just `Chicago` which will show up on the frontend as well. Also, this branch intends to fix the web-pub manifest links so that the Read Online link on the frontend will go to the actual web-pub instead of it's JSON form in AWS S3.

SFR-1708_FixISACPubLocaton&Links

---

scripts/updatePubLocationAndLinks.py

This hotfix adds one if conditional to avoid running the `updatePubLocation&Links` script for ISAC records with an empty `has_part` array.

HOTFIX_ISACHasPartConditional

---

README.md

Got bitten a bit on the last release when I realized the github actions succeeded even though the eventual ECS update failed, since the deploy action just triggers an ECS update, but doesn't poll till it succeeds.
Note, I didn't link the exact ECS cluster / service because this repo is public and I figure we don't wanna leak the names of our IAM resources?
Also, it may make sense to just use something like https://github.com/marketplace/actions/ecs-wait in the future, thoughts?

Add blurb about checking ECS console during deploy

---

CHANGELOG.md
scripts/deleteProblemWorks.py

This hotfix adds a script to remove problem works from PSQL and ES database which I recently created when clustering a record from LOC.

HOTFIX_DeleteWorkFromQAFrontend

---

CHANGELOG.md
mappings/nypl.py
scripts/__init__.py
scripts/nyplLoginFlags.py
tests/unit/test_nypl_mapping.py

This PR adds a script to add an nypl_login flag to the Links objects of DRB. For right now, the nypl_login flag will only be inserted for links that have requestable formats like application/html+edd and application/x.html+edd with a True boolean value. My second commit adds the nypl_login flag to nypl records that are requestable and these records seem to be the only ones that have the requestable formats.

SFR_1826_NYPLLoginFlag

---

CHANGELOG.md
processes/nypl.py
tests/unit/test_nypl_process.py

This PR intends to fix a sqlalchemy.exc:ObjectNotExecutableError which is an issue that is preventing the NYPL process from running in QA and prod which has prevented the addition of new records directly from NYPL since late last year. This StackOverflow forum [https://stackoverflow.com/questions/69490450/objectnotexecutableerror-when-executing-any-sql-query-using-asyncengine](url) had the same problem I encountered and the solution is what I followed for this PR.

SFR_1864_NoNYPLRecordsCreated

---

CHANGELOG.md
api/app.py
api/blueprints/__init__.py
api/blueprints/drbFulfill.py
config/sample-compose.yaml
tests/unit/test_api_fulfill_blueprint.py

Does not have 100% test coverage; when everything is hooked up I will add test cases for the positive cases of "yes, this is working" and also figure out how to mock the expired token.
Don't love how much logic lives directly in the Blueprint but given the error structure I'm not sure how to best test it if I were to bundle the auth logic in another file, but open to refactoring.

Add fulfill route and tests

---

config/sample-compose.yaml

Change an outdated Hathi file listing to a JSON file at a new URL containing the same information.

Change Hathi data files source to new URL

---

CHANGELOG.md
config/production.yaml
config/qa.yaml

This PR updates the Bardo CCE API and Hathi Data Files URLS in the production and qa config. The Bardo CCE API URL was outdated so local running of the NYPL Process was unsuccessful and worked soon after updating this url.

SFR-1866_Bardo&HathiConfigUpdate

---

api/utils.py

This hotfix focuses on updating the source priority to include University of Michigan because a KeyError occurred when trying to search up a UofM book on the QA site.

HOTFIX_SourcePriorityUofM

---

api/utils.py
tests/unit/test_api_utils.py

Fixes an issue where links with nypl_login for Limited Access were not given valid fulfill links in the Work level view

Overwrite with fulfill link in FormatWork

---

CHANGELOG.md
processes/UofM.py
scripts/nyplLoginFlags.py
tests/unit/test_UofM_process.py

This PR adds nypl_login flags to the University of Michigan mapping and to the current Michigan links already in the database.

SFR-1890_MichiganNYPLFlags

---

CHANGELOG.md
scripts/__init__.py
scripts/deleteUMPManifestLinks.py

This PR adds a new script to delete UMP manifest links from the links table that should not have been created at this time. One question is if the UofM manifest directory in the S3 manifest bucket should be deleted as well?

SFR-1891_DeleteUMPManifestLinks

---

README.md

I assume that this is referencing Tugboat's builds, which no longer automatically open on PR.

Remove reference to Tugboat temporary builds from README

---

CHANGELOG.md
api/utils.py
tests/unit/test_api_utils.py

This hotfix intends to fix the 500 error that started to occur in the DRB API after using the search endpoint and using the format filter. The error came in after adding the items media type sorting code line which led to a index error due to some items having an empty link list. Removing this line might revert some changes to the frontend with item sorting but the links are properly sorted now due to the change to the sortByMediaType method in APIUtils from a previous hotfix change [https://github.com/NYPL/drb-etl-pipeline/pull/294](url)

HOTFIX_FixFormatFilter500Error

---

CHANGELOG.md
scripts/__init__.py
scripts/fulfillURLManifest.py

This PR focuses on updating the UofM manifests with fulfill endpoints to replace the pdf and epub links within the manifest JSON file. All the UofM files will be affected for now even though a few are now Public Domain since reverting this change can be done at a later time once this ticket is resolved. Also, the commented out class definition at the top of the script has to do with one question I have. The question is if the S3Manger method, `putObjectInBucket`, should be utilized instead of the regular `s3_client.put_object` method since the S3Manger method is used when we currently put manifests in a S3 bucket like in the UofM process.

SFR-1966_FulfillURLUofM

---

CHANGELOG.md
README.md

After going through the installation process for drb-etl-pipeline, I have updated the README accordingly based on steps that have changed or require more information to complete.

SFR-1990_UpdateREADME

---

CHANGELOG.md
README.md
config/production.yaml
config/qa.yaml
config/sample-compose.yaml
managers/s3.py
processes/UofM.py
processes/__init__.py
processes/addFulfillManifest.py
scripts/fulfillURLManifest.py
tests/unit/test_fulfillManifest_process.py

This PR focuses on adding fulfill endpoints to future LA manifests after they have been ingested and clustered. A new flag called fulfill_limited_access has been added to prevent these LA works to be Read Online on the frontend before the process  addFulfillManifest is run.

SFR-1967_FulfillFutureLAManifests

---

CHANGELOG.md
config/production.yaml
config/qa.yaml
processes/__init__.py
processes/fulfillURLManifest.py
scripts/__init__.py
scripts/addFulfillManifest.py
tests/unit/test_fulfillManifest_process.py

This hotfix intends to fix the typos found in the original format of the fulfill endpoints in the UofM manifests. The structure of it now works as intended with an example that was used by the web reader on the front end. The example was this: `https://drb-api-qa.nypl.org/fulfill/9350262`

HOTFIX_FixFulfillURLManifest

---

CHANGELOG.md
migrations/versions/54e57fb2e1c6_add_contract_source_to_records_and_items.py
model/postgres/item.py
model/postgres/record.py

This PR so far focuses on adding a new column named publisher_project_source to the record and items PSQL tables since both tables have a source field already so it makes sense to have both source type fields in these tables.

Sfr-2054_PubSourceFieldMigration

---

CHANGELOG.md
api/blueprints/drbEdition.py
tests/unit/test_api_edition_blueprint.py

- After adding better error handling, the logs now show that the editionID that was being passed in was a string and not an integer
- This change ensures the path param editionID is a valid integer before querying the database. If not, it returns a 400 response back to the client
`make test`

SFR-1935 Add editionID validation

---

managers/sfrRecord.py
tests/unit/test_sfrRecord_manager.py

This PR is a quick one to make sure when the Publisher Press Backlist Books are ingested and clustered that the publisher_project_source field in the items table is properly filled out since the previous SFR-2055 ticket only filled it out the field in the records table

Sfr 2055v2 Pub Project Source UofM Items

---

CHANGELOG.md
config/sample-compose.yaml
docker-compose.yml

This PR changes the name of the DRB API container from drb_local_webapp to drb_local_api since the previous name was a misnomer and could confuse new developers of what the container actually represents.

SFR-2069_RenameDockerAPIName

---

CHANGELOG.md
README.md

This PR adds a few lines to the README to explain how to attain the local-compose.yaml file credentials and the file itself.

SFR_2068_DocumentLocalComposeSteps

---

CHANGELOG.md
api/blueprints/drbUtils.py

- Adding more logging to understand why proxying through S3 PDFs fails
- When we retrieve metadata about the S3 url it returns 403
- When we retrieve metadata about the cleaned S3 url it returns 400 and the cleaning process malforms the tokens
- @jackiequach had a great callout and we should just not proxy to S3. 
`make test`

SFR-2065: Adding more logging to proxy API

---

.github/workflows/pull-request-checks.yaml
.github/workflows/tests-unit.yaml
CHANGELOG.md
Makefile
README.md

- Adds integration test make command
`make unit; make integration`
- We will tackle integration tests and CI in a later phase of tech debt but not as part of the OCLC work.

SFR-2079: Integration test make command

---

CHANGELOG.md
docker-compose.yml

- Upgrading RabbitMQ Docker image to latest release https://www.rabbitmq.com/release-information
`docker compose up`

SFR-2066: Upgrade RabbitMQ Docker image to 3.13

---

CHANGELOG.md
api/db.py
managers/db.py

- The API db client's enter and exit function were deleted as part of https://github.com/NYPL/drb-etl-pipeline/pull/321
- This change readds them but removes the enter and exit function from the db manager
`make test`

NO-REF: Fix to readd API db client enter/exit functions

---

CHANGELOG.md
config/development.yaml
config/example.yaml
processes/developmentSetup.py

This PR was focused on fixing the `fetchHathiSampleData` method which raised an `IOError of Unable to load data files` so the other processes like the `ClusterProcess` don’t ever run in the `DevelopmentSetUpProcess` in the `local.yaml` files. The error came from the `HATHI_DATAFILES` link being outdated and giving a 404 error: [https://www.hathitrust.org/filebrowser/download/244651](). I updated the link to the Hathitrust dataset file in the qa and prod yaml files which includes multiple datasets in it. To adjust the amount of Hathitrust books ingested the conditional break statement at the end of the `DevelopmentSetUpProcess` can be adjusted.

SFR-2114: HathiTrust Fetch Data Files Fix

---

CHANGELOG.md
api/blueprints/drbCitation.py
tests/unit/test_api_citation_blueprint.py

- Added error handling to the citation endpoint
- Added a TODO to refactor the util functions and move them out into a separate file
`make test`

SFR-2121: Adding citation endpoint error handling

---

CHANGELOG.md
api/blueprints/drbCollection.py
tests/unit/test_api_collection_blueprint.py

- Adding error handling to the collection endpoints that are called from the frontend
`make test`

SFR-2122: Adding collection GET API error handling

---

CHANGELOG.md
api/blueprints/drbSearch.py
tests/unit/test_api_search_blueprint.py

- The search API had some decent error handling but some incorrect HTTP response codes
- Refactored and moved to camel case
- Added outer error handling
`make test`

SFR-2120: Adding search API error handling

---

CHANGELOG.md
api/blueprints/drbCitation.py
api/blueprints/drbCollection.py
api/blueprints/drbWork.py
api/validation_utils.py
tests/unit/test_api_citation_blueprint.py
tests/unit/test_api_collection_blueprint.py
tests/unit/test_api_work_blueprint.py

- The database client does expect a valid uuid before querying, otherwise it will throw an error making it look like there's something wrong on the server
- This change adds validation to check the uuid is valid
`make unit`

SFR-2133: Adding UUID validation to APIs

---

CHANGELOG.md
processes/oclcClassify.py
tests/unit/test_oclcClassify_process.py

- Switching over to the v2 classify record implementation 
`make unit`

NO-REF: Switching to v2 classify record

---

CHANGELOG.md
managers/oclc_catalog.py
processes/core.py
processes/oclcClassify.py

Todo:
- Check exception in query building function is handled correctly if query can't be formed
- Ensure graceful failure if OCLC json does not contain error type

NOREF-Better error handling & logging

---

CHANGELOG.md
managers/oclc_catalog.py
mappings/oclcCatalog.py
mappings/xml.py
processes/developmentSetup.py
processes/oclcCatalog.py
processes/oclcClassify.py
tests/unit/test_oclcCatalog_process.py

- Improves error handling and logging in the OCLC classify process
- Switches to using detail from OCLC error response, e.g:
```
{
"type": "INVALID_QUERY_PARAMETER_VALUE",
"title": "Validation Failure",
"detail": "oclcNumber must be a positive whole number"
}
```
`make test`

SFR-2173: Improving error handling and logging in OCLC classify process

---

CHANGELOG.md
managers/oclc_catalog.py
mappings/oclcCatalog.py
processes/oclcCatalog.py
processes/oclcClassify.py
tests/unit/test_oclcCatalog_manager.py

- We discovered that the ratio of OCLC catalog records in QA vs local did not make sense
- There was bug in the OCLC catalog manager where the attempts kept increasing since it was a class variable and we we would not actually call OCLC. 
Ran ETL pipeline against subset of HathiTrust record to see the increase in OCLC catalog records:

NO-REF: Fixing OCLC catalog query attempts bug

---

main.py
processes/hathiTrust.py
tests/unit/test_hathitrust_process.py

- Adds ingest limit and logging to HathiTrust ingest
`python main.py -p HathiTrustProcess -e local -i complete -l 10`

SFR-2216: Adding ingest limit and logging to HathiTrust ingest

---

mappings/loc.py
processes/loc.py
tests/unit/test_loc_process.py

- Fixing a couple minor bugs with mapping LOC records
- Skipping ingest of records where we can't map authors 
`make test; python main.py -p LOCProcess -e local -i complete -l 10`

SFR-2216: Fixing LOC process ingestion

---

processes/nypl.py
tests/unit/test_nypl_process.py

- SQLAlchemy is returning a tuple and not a JSON as per the original code. 
- I added a _map_bib function that will try to unpack a tuple first and then default to the bib. 
- Streamlined the query to only return fields we are interested in
`python main.py -p NYPLProcess -e local -i complete -l 10`

SFR-2216: Fixing NYPL ingest process locally

---

managers/doabParser.py
managers/parsers/openEditionParser.py
processes/doab.py
tests/unit/test_doab_process.py

- DOAB is returning 200 from the browser but not from Python code
- Adding a user agent header to mimic the header that the browser sends 
- Fixes bug where book-access element does not exist
- Fixes bug where finding final URI had too many redirects and hit the recursion call stack limit of 1000
`python main.py -p DOABProcess -e local -i complete -l 10`

SFR-2234 SFR-2235: Fix bugs in DOAB ingestion process

---

docker-compose.yml
processes/developmentSetup.py
processes/sfrCluster.py

- Refactors dev setup process
- Removes the dev setup process docker container as it doesn't need to run every time you run docker compose up
- Fixes infinite cluster loop bug where the cluster_status would always remain false if we failed to cluster
`python main.py -p DevelopmentSetupProcess -e local`

SFR-2245: Refactor dev setup process and fix infinite cluster loop

---

managers/sfrRecord.py

This hotfix PR is meant to fix a bug when making a deep copy of the workIdentifiers array since there are Instance objects and deep copy isn't naturally designed to make copies of Instance objects. In this case, it would be better to make a new array that references the Instance objects instead with a shallow copy.

SFR-2247: Fixing deep copy work identifiers bug

---

processes/met.py
tests/unit/test_met_process.py

- Adds MET process ingestion count log 
```
python main.py -p METProcess -e local -i complete -l 100
{"timestamp":1729009077778,"message":"Starting process METProcess in local","log.level":"INFO","logger.name":"__main__","thread.id":140704660770304,"thread.name":"MainThread","process.id":41582,"process.name":"MainProcess","file.name":"/Users/kylejacksonvillegas/workspace/drb-etl-pipeline-venv/drb-etl-pipeline/main.py","line.number":32,"entity.type":"SERVICE"}
{"timestamp":1729009099641,"message":"Ingested 57 MET records","log.level":"INFO","logger.name":"processes.met","thread.id":140704660770304,"thread.name":"MainThread","process.id":41582,"process.name":"MainProcess","file.name":"/Users/kylejacksonvillegas/workspace/drb-etl-pipeline-venv/drb-etl-pipeline/processes/met.py","line.number": …
```

SFR-2220: Adding MET process ingestion count log

---

analytics/upress_reporting/counter_5_controller.py
analytics/upress_reporting/models/data/interaction_event.py
analytics/upress_reporting/models/pollers/interaction_event_poller.py
analytics/upress_reporting/models/reports/counter_5_report.py
analytics/upress_reporting/models/reports/country_level.py
analytics/upress_reporting/models/reports/downloads.py
analytics/upress_reporting/models/reports/total_usage.py
analytics/upress_reporting/models/reports/views.py

**Changes Made**
- Updated file names to reflect report titles (as per business partner feedback)
- Added `Metrics_Type` row to overhead description (as per business partner feedback) and removed `Metrics_Type` column
[Sample reports link](https://docs.google.com/spreadsheets/d/1-geK3StSJVIRxr9ylkKuqZ_X880qKnGriMc9HcvDd7g/edit?usp=sharing)

SFR-2188: Removed Metrics_Type Column + Updated File Names

---

managers/sfrRecord.py
processes/seed_local_data.py
tests/unit/test_sfrRecord_manager.py

- Because we have a PK on id and not uuid we were not merging correctly and instead creating duplicate works with the same uuid but different ids
- This change sets the work id as the matched work id to merge properly
`make test; python main.py -p SeedLocalDataProcess -e local (run multiple times)

SFR-2267: Fixing duplicate work bug

---

processes/classify.py
tests/unit/processes/test_classify_process.py

- Adds a persistent count of records that have been updated during the process
- Adds a summary of this count before process exists
- Debug-level statement previously only logged per "chunk", aka when a full window of records was saved. Moved this debug statement to the function that actually persists these so that all occurrences of this are logged, since ingests of 5-10 records e.g. resulted in no debug statements

Classify logging improvements

---

managers/elasticsearch.py
managers/kMeans.py
managers/sfrRecord.py
processes/cluster.py

- Removes stop_words parameter since it can only be used by the word analyzer. This change removes these warnings:
```
The parameter 'stop_words' will not be used since 'analyzer' != 'word'
```
`python main.py -p SeedLocalDataProcess -e local`
```
{"timestamp":1729629646693,"message":"Clustered 10 works","log.level":"INFO","logger.name":"processes.cluster","thread.id":140704660770304,"thread.name":"MainThread","process.id":69301,"process.name":"MainProcess","file.name":"/Users/kylejacksonvillegas/workspace/drb-etl-pipeline-venv/drb-etl-pipeline/processes/cluster.py","line.number":95,"entity.type":"SERVICE"}
```

SFR-2278: Improving cluster process logging

---

managers/sfrRecord.py
processes/cluster.py
tests/unit/test_sfrRecord_manager.py

- This change fixes duplicate works but does not merge the records like intended. 
- We will create a new work with a new PK but the same uuid. All editions and items will be new based on the most recent cluster. Because the entities are new, they will have new ids.
- The old works, editions, items will be deleted and new ones will be created. 
- Tested against a few records in QA

SFR-2285: Fix duplicate works

---

managers/sfrRecord.py
processes/cluster.py

- Extends the number of items by the maximum number in the has_part list of the record. 
- Tested against a record in QA that failed to cluster due to an index out of range error 
https://drb-qa.nypl.org/work/b21b52f1-e6f1-4363-8737-c708616b71b3

SFR-2285: Fix has part item build

---

managers/s3.py
mappings/chicagoISAC.py
processes/ingest/chicago_isac.py
processes/ingest/doab.py
processes/ingest/loc.py
processes/ingest/met.py
processes/ingest/u_of_m.py
processes/ingest/u_of_sc.py
tests/unit/processes/ingest/test_chicago_isac_process.py

This PR removes comments, uses composition instead of inheritance for the __init__ method, and transfers some code into a new method.

SFR-2265: Refactored Chicago ISAC mapping and processes

---

main.py
processes/cluster.py

- Clustering fails if we try to tokenize a null title
- This change skips trying to cluster records without a title 
`python main.py -p ClusterProcess -e local-qa -i single -r 1ad13bf1-e48b-4f8f-8868-457d98b302a8`
```
{"timestamp":1730226129848,"message":"Starting process ClusterProcess in local-qa","log.level":"INFO","logger.name":"__main__","thread.id":140704663367552,"thread.name":"MainThread","process.id":13466,"process.name":"MainProcess","file.name":"/Users/kylejacksonvillegas/workspace/drb-etl-pipeline-venv/drb-etl-pipeline/main.py","line.number":32,"entity.type":"SERVICE"}
{"timestamp":1730226132070,"message":"Clustering 1ad13bf1-e48b-4f8f-8868-457d98b302a8","log.level":"INFO","logger.name":"processes.cluster","thread.id":140704663367552,"thread.name":"MainThread","process.id":1346 …
```

SFR-2292: Skip clustering records with no title

---

managers/rabbitmq.py
processes/file/s3_files.py
tests/unit/processes/file/test_s3_files_process.py
utils/__init__.py
utils/retry_request.py

- We don't want to silently fail to generate a webpub 
- If we can't, we should not acknowledge the message and retry the processing of the message
`make unit`

SFR-2291: Throw error if we fail to generate webpub 

---

processes/frbr/classify.py
tests/unit/processes/frbr/test_classify_process.py

- Refactoring classify process

SFR-2284: Refactoring classify process

---

processes/cluster.py
tests/unit/processes/test_cluster_process.py

- We are still seeing some NYPL records that we fail to cluster because the title is None
- Adding a filter to filter out records where the title is None in the first place.

SFR-2294: Only cluster records that have a title

---

requirements.txt

- Unit tests started failing because werkzeup.__version__ attribute was no longer there. 
- This cahnge pins the package to 2.2.2 which should fix the unit tests.

NO-REF: Pin werkzeug to 2.2.2

---

.github/workflows/tests-unit.yaml

- We should not run unit tests on every change to the repo
- This change triggers the unit tests GH action workflow only if files change in certain folders
- We should see a reduction hopefully in cost

NO-REF: Only run unit tests if requirements or source code changes

---

processes/cluster.py
processes/core.py
tests/unit/processes/test_core_process.py

- Removes elastic search manager from the core process inheritance tree.
`make unit`; `python main.py -p SeedLocalDataProcess -e local`

NO-REF: Remove Elastic Search Manager Ancestor

---

main.py

- Sometimes I see that a process is starting from main.py but no other logs from the process files
- Adding some error handling to see if initiatlization fails. 
- We have a lot of code in our constructors, so this is an outer try/except block that will catch errors that occur initializing our processes.

NO-REF: add error handling error process init

---

mappings/base_mapping.py
mappings/csv.py
mappings/json.py
mappings/marc.py
mappings/oclc_bib.py
mappings/record_mapping.py
mappings/sql.py
mappings/xml.py
processes/ingest/doab.py
processes/ingest/loc.py
processes/ingest/met.py
processes/ingest/u_of_m.py
processes/ingest/u_of_sc.py
services/sources/source_service.py
tests/unit/processes/file/test_fulfill_manifest_process.py
tests/unit/processes/ingest/test_chicago_isac_process.py
tests/unit/processes/ingest/test_doab_process.py
tests/unit/processes/ingest/test_loc_process.py
tests/unit/processes/ingest/test_met_process.py
tests/unit/processes/ingest/test_u_of_m_process.py
tests/unit/test_base_mapping_mapping.py
tests/unit/test_custom_formatter_mapping.py
tests/unit/test_doab_mapping.py

- Core and AbstractMapping were not clear names
- Renames Core to BaseMapping
- Renames AbstractMapping to RecordMapping
`make unit`

NO-REF: Rename base mapping classes

---

processes/cluster.py
processes/core.py
processes/file/covers.py
processes/frbr/classify.py
processes/local_development/seed_local_data.py
tests/unit/processes/file/test_cover_process.py
tests/unit/processes/frbr/test_classify_process.py
tests/unit/processes/test_core_process.py

- Removes RedisManager as an ancestor of CoreProcess
- Uses composition for the RedisManager instances with the processes that rely on this manager
`make unit`

NO-REF: Remove RedisManager as an ancestor of CoreProcess

---

model/__init__.py
model/queue/file_message.py
processes/core.py
processes/frbr/catalog.py
processes/frbr/classify.py
processes/ingest/doab.py
processes/ingest/gutenberg.py
processes/ingest/loc.py
processes/ingest/met.py
processes/ingest/muse.py
tests/unit/processes/frbr/test_catalog_process.py
tests/unit/processes/frbr/test_classify_process.py
tests/unit/processes/ingest/test_doab_process.py
tests/unit/processes/ingest/test_gutenberg_process.py
tests/unit/processes/ingest/test_loc_process.py
tests/unit/processes/ingest/test_met_process.py
tests/unit/processes/ingest/test_muse_process.py
tests/unit/processes/test_core_process.py

- Removes RabbitMQManager as a CoreProcess ancestor
- Uses composition with processes that use the RabbitMQManager
`make unit`

NO-REF: Removing RabbitMQManager as a CoreProcess ancestor

---

processes/frbr/classify.py
tests/unit/processes/frbr/test_classify_process.py

- Switches to first query to loop through unfrbrized records
- Adds ingest limit
- Commits changes to frbrized records 1 at a time
- Saves bulk objects separately
- There was a bug with the window query returning different objects than records. During bulk save, those different objects were lacking ids and the necessary sqlalchemy decorations.  
`make unit` `python main.py -p SeedLocalDataProcess -e local`

NO-REF: Fix and simplify classify record updates

---

newrelic.ini

- We get an incredible amount of debug and info logs from New Relic agent
- We don't care about these logs
- Setting the log level to warning accordingly

SFR-2344: Set New Relic Log Level to Warning

---

api/app.py
api/blueprints/drbSearch.py
config/frontend-ci.yaml
managers/elasticsearch.py
requirements.txt

- This change sets up a local backend for frontend CI
- It connects to elastic search via the VPC endpoint which will require some authorization/authentication via AWS sig4.
- It uses a combination of connecting to the QA database and elastic search index and a local redis. 
`docker compose up redis; python main.py -p APIProcess -e frontend-ci`

SFR-2316: Create a local backend for frontend CI

---

processes/ingest/hathi_trust.py

- There was an error this morning where a CSV field was too large
- This change increases the field size limit to the max size of the system
- Also if we are unable to parse a date, we just set it to None and ignore it
`python main.py -p HathiTrustProcess -e local -i daily`

SFR-2349: Increasing CSV Field Size Limit

---

managers/sfrRecord.py

- Some NYPL records have some different has_version columns, e.g. `2d ed.||2|2`
- These versions were causing issues while unpacking the edition statement and number
- Updated the code to handle these cases
`python main.py -p ClusterProcess -e local-qa -i daily`

SFR-2346: Fix edition verion unpacking

---

.gitignore
scripts/migrate_digital_assets.py

- Migrates files from S3 to google drive 
`python scripts/migrate_digital_assets.py`

SFR-2352: Script to upload digital assets to Google Drive

---

processes/core.py
processes/file/covers.py
processes/file/fulfill_url_manifest.py
processes/ingest/chicago_isac.py
processes/ingest/doab.py
processes/ingest/loc.py
processes/ingest/met.py
processes/ingest/muse.py
processes/ingest/publisher_backlist.py
processes/ingest/u_of_m.py
processes/ingest/u_of_sc.py
tests/unit/processes/file/test_cover_process.py
tests/unit/processes/file/test_fulfill_manifest_process.py
tests/unit/processes/ingest/test_chicago_isac_process.py
tests/unit/processes/ingest/test_doab_process.py
tests/unit/processes/ingest/test_loc_process.py
tests/unit/processes/ingest/test_met_process.py
tests/unit/processes/ingest/test_muse_process.py
tests/unit/processes/ingest/test_u_of_m_process.py

- Removes S3Manager as a CoreProcess ancestor
- Uses composition with the classes that need the S3Manager
- Removes unnecessary tests
`make unit`

SFR-2327: Removing S3Manager as an Ancestor of CoreProcess

---

mappings/publisher_backlist.py
processes/ingest/publisher_backlist.py
services/sources/publisher_backlist_service.py
tests/unit/processes/test_pub_backlist_mapping.py
tests/unit/test_pub_backlist_mapping.py

This PR is focused on creating a unified mapping for the Publisher Backlist Project records. One issue I'm running into is that the 'Projects' field when retrieved from Airtable comes back as a code like this ['recaXuQYVJMiFs6D8'] instead of ['MIT Press']. I would like to receive some help on how to access the actual name of the project instead of the code so I can properly format the source field of these records in the DRB database.

SFR-2308_PubBacklistMapping

---

managers/oclc_auth.py
managers/oclc_catalog.py
mappings/oclcCatalog.py
tests/unit/test_oclcCatalog_manager.py
tests/unit/test_oclcCatalog_mapping.py

- Removes search v1 endpoint and instead uses metadata v2
- Requests key with reduced scope (this is now required, since key no longer has access to full read/write API actions)
- Strips OCLC prefixes from OCLC control numbers when applying mapping: there are a few thousand records in QA that are prefixed, from various sources. However, the great majority of OCLC numbers are not prefixed and I created a function to remove the prefixes, as we do for e.g. Project MUSE
Tested with the SeedLocalData process and fields were manually compared -- after removing OCLC control number prefixes, they now look comparable at a glance.

SFR-2288 Querying by OCLC Number uses metadata API MARCXML endpoint

---

processes/frbr/classify.py

- This change removes the empty related bib warning log which is quite noisy and also normal in the majority of cases

SFR-2386 Remove empty related bib warning log

---

processes/file/fulfill_url_manifest.py
services/sources/publisher_backlist_service.py

With this PR I modified the `store_pdf_manifest` method and the prefix attribute of the `FulfillManifestProcess` object to incorporate a new S3 folder called pubBacklist that will include all the manifests from the publisher backlist project such as UofM and UofSC. [https://us-east-1.console.aws.amazon.com/s3/buckets/drb-files-qa?prefix=manifests/&region=us-east-1&bucketType=general](url)

SFR-2384: Fulfill Manifest Pub Backlist S3 Bucket

---

services/sources/publisher_backlist_service.py

This PR focuses on replacing the use of the Next Steps Airtable field with the DRB_Ready To Ingest field to represent the status of a Publisher Backlist record that is ready to be ingested.

SFR-2382: Incoporate Ready To Ingest Field from Airtable

---

processes/frbr/classify.py
services/ssm_service.py
tests/integration/test_ssm_service.py

Adds method for using SSM service to retrieve parameters directly instead of adding them each to Terraform file and/or a local development file.

Sfr 2374 access parameter store

---

processes/ingest/publisher_backlist.py
services/sources/publisher_backlist_service.py

This PR focuses on deleting Publisher Backlist works from the PSQL and ES databases when the Airtable Deleted field's value is set to the boolean true.

SFR-2392_Delete Publisher Backlist Works

---

services/google_drive_service.py

Type hinting is throwing an error during certain integration tests due to Optional being used without being imported

NOREF - Fix type hint error

---

scripts/__init__.py
services/sources/publisher_backlist_service.py

This PR focuses on the automated deleted edge case for when a Publisher Backlist record produces a new edition with an already existing work that has other editions during the ingestion process. The PSQL deletion has been enacted but the deletion of the same edition in ES is commented out since the fields for editions are not as clear with how to search for it compared finding the same work in the PSQL and ES databases. That will be my focus with future commits.

SFR-2393: Delete Publisher Backlist Editions

---

tests/integration/api/test_get_collection.py
tests/integration/api/test_get_edition.py
tests/integration/api/test_get_link.py
tests/integration/api/test_get_work.py
tests/integration/api/test_search.py
tests/integration/api/test_search_collection.py

This PR adds edge cases for following API end points
- /edition/{id}
- /link/{id}
- /search
- /work/{uuid}

SFR-2311: API Edge Test Cases

---

api/app.py
api/blueprints/__init__.py
api/blueprints/drbCollection.py
swagger.v4.json

- Migrates collection endpoint to use plural noun
`docker compose up` and hit the endpoint /collections/list

SFR-2412: Migrate collection endpoint to use plural noun

---

api/app.py
api/blueprints/__init__.py
api/blueprints/drbWork.py
swagger.v4.json

- Migrates work endpoint to use plural noun
- Moves /collections/list GET method to /collections in swagger
`docker compose up` and hit the endpoint /works

SFR-2414: Migrate work endpoint to use plural noun

---

main.py
mappings/publisher_backlist.py
processes/ingest/publisher_backlist.py
services/google_drive_service.py
services/sources/publisher_backlist_service.py
services/ssm_service.py

- Fixes a few bugs to get the backlist project working as expected
- Updates the delete logic to delete by items then editions and then works
- Still needs some refactoring - I think that I can get it to be cleaner
- Tested ingesting and clustering a record
- Tested deleting a record

[SFR-2434] Simplifying delete record implementation

---

api/utils.py
mappings/publisher_backlist.py
processes/file/fulfill_url_manifest.py
tests/unit/processes/file/test_fulfill_manifest_process.py

- The Fulfill URL Manifest process was using different incorrect class variables
- This change fixes typos!
`python main.py -p FulfillURLManifestProcess -e local -i complete`
`python main.py -p FulfillURLManifestProcess -e local -i daily`
`make unit`

SFR-2438: Fix Fulfill URL Manifest Process

---

mappings/chicagoISAC.py
mappings/clacso.py

This PR focuses on creating a mapping for the new source CLACSO that will soon be added to the DRB ETL pipeline for ingestion.

SFR-2452: CLACSO Mapping

---

managers/oclc_catalog.py
tests/unit/test_oclcCatalog_manager.py

- We are seeing some timeouts with the new endpoint to query the OCLC catalog
- Bumps the timeout to 5 seconds!

SFR-2426: Increasing OCLC query catalog timeout to 5 seconds

---

processes/__init__.py
processes/ingest/clacso.py

This PR focuses on the foundation of the CLACSO Ingest Process. Any code lines that involve the CLACSOService are commented out as this service will be expanded upon in future PRs that will incorporate the logic for retrieving CLACSO records.

SFR-2453: CLACSO Ingest Process

---

.github/workflows/build-qa.yaml
.github/workflows/ci.yaml
Makefile
tests/conftest.py
tests/functional/processes/ingest/assert_ingested_records.py
tests/functional/processes/ingest/test_chicago_isac_process.py
tests/functional/processes/ingest/test_doab_process.py
tests/functional/processes/ingest/test_gutenberg_process.py
tests/functional/processes/ingest/test_loc_process.py
tests/functional/processes/ingest/test_met_process.py
tests/functional/processes/ingest/test_muse_process.py
tests/functional/processes/ingest/test_nypl_process.py
tests/functional/processes/ingest/test_publisher_backlist_process.py
tests/integration/services/sources/test_nypl_bib_service.py
tests/integration/services/sources/test_publisher_backlist_service.py
tests/integration/test_google_integration.py
tests/integration/test_oclc_auth_manager.py
tests/integration/test_oclc_catalog_manager.py
tests/integration/test_ssm_service.py

- Run CI via Github Actions
- This first pass runs the API tests that run against QA
- Making a few changes to load different env variables depending on the environment 
- There's going to be some additional work to get all of the tests running in the QA environment

SFR-2741: Run CI via Github Actions

---

config/example.yaml
config/production.yaml
config/qa.yaml
managers/gutenberg.py
tests/helper.py
tests/unit/test_gutenberg_manager.py

- https://api.github.com/graphql is constant across environments, so setting as a constant!

SFr-2478: Setting github api url as a constant

---

load_env.py

- This change only sets the env var secret if the parameter retrieved from SSM is not null

NO-REF: set secret env param only if it's not null

---

managers/elasticsearch.py

- Ok so the Index inner class name field is set before the os environment variables are set. Therefore, the index is none if we try to create it at that point. 
- This change just passes in the index from the elastic search manager when initializing the ESWork.

NO-REF: Fix local elastic search index creation

---

scripts/cleanup_duplicate_works.py

- Sets a batch size of 100 when cleaning up duplicate works
- The ECS task ran out of memory!
- ran script in QA

NO-REF: setting a batch size for deleting works

---

main.py
processes/cluster.py
tests/unit/processes/test_cluster_process.py

- Adds ability to cluster records by source
- Cleanups the process logic so that we move away from process types - customer/complete.
`make unit`
`python main.py -p ClusterProcess -e local-qa -src loc -l 1`

SFR-2484: Adding ability to cluster records by source

---

processes/ingest/doab.py
tests/functional/processes/ingest/test_doab_process.py

- Sets functional doab test ingest limit to 1 for speed purposes
- Increments records processed by 1 instead of 100 inside the inner for loop

NO-REF: Fixing doab ingest limit

---

model/__init__.py
model/postgres/record.py
tests/functional/processes/ingest/test_met_process.py

- Tests that the MET Process saves manifest for each record
- Adds a Part dataclass to be able to get the manifest easier
```
pytest tests/functional/processes/ingest/test_met_process.py -s
```

NO-REF: Test that MET process saves manifest for each record 

---

tests/conftest.py

- Unfortunately, we are still hindered by the VPN blocking access to the database from our GH action hosts
- These changes default to a set of data already in QA when we can't connect to the DB, so CI should pass
`pytest tests/integration/api --env=local-qa`

NO-REF: Fix CI tests when unable to connect to DB

---

tests/conftest.py

- Tests to ensure we can connect to the DB in the pytest fixture
` pytest tests/integration/api/test_get_edition.py --env=local-qa`

 NO-REF: Test DB connection in pytest fixture

---

.github/workflows/ci.yaml
.github/workflows/tests.yaml

- actions/cache@v2 is deprecated as of February 1st, 2025
- upgrades to v4

NO-REF: Update GH Actions Cache

---

load_env.py

Load local secrets before SSMServce instantiation to fix errors for retrieving values from parameter store

NO-REF: Load local secrets before SSMServce instantiation

---

processes/ingest/doab.py
tests/unit/processes/ingest/test_doab_process.py

Updates the DOABProcess to use RecordBuffer instead of inheriting from the CoreProcess class.
Ran unit, integration, and functional tests

NO-REF: Update DOABProcess to use RecordBuffer

---

.github/workflows/full-ci-cd.yaml

This PR does the following
-     adds concurrency in ci/cd on workflow level
-     ensures one instance of the pipeline can run at a time for the main branch
-     new pushes will cancel any in-progress pipeline runs
-     production deployments will complete before new ones start
-     avoids race conditions in deployment processes

Add concurrency in GHA

---

mappings/clacso.py

This hotfix adds the Spanish and Portuguese word for 'book' as one of the possible medium types that a CLACSO record mapping should have.

NO-REF: Add book medium in Spanish and Portuguese

---

processes/ingest/clacso.py

- Reverting back to CLACSO download only flags
- We will circle back if we have time this quarter to see if we can improve the reader performance and ensure we are able to proxy or download the files

NO-REF: Reverting back to CLACSO download only

---

.github/workflows/tests.yaml
config/qa.yaml
docker-compose.yml
managers/oclc_catalog.py
processes/frbr/classify.py
processes/local_development/local_development_setup.py
tests/functional/processes/frbr/test_frbr_process.py
tests/unit/processes/frbr/test_classify_process.py

- https://newyorkpubliclibrary.atlassian.net/browse/DOPS-1112 Devops needs to upgrade the postgres version to 16 since 12 is no longer supported. 
- We decided it was time to create a separate database cluster altogether for QA 
- This change points the QA stack to the new database cluster via modifying the config. 
- Once we have tested that everything looks good in QA we can upgrade the production database cluster version. 
- The postgres volume's files will no longer be compatible with the postgres docker container
- Each developer must delete their volume and rerun the local developer setup process to reinitialize the database. 
`python main.py -p CLACSOProcess -e local-qa -i complete -l 1`

SFR-2537 Pointing the QA stack to the new QA database

---

config/qa.yaml

- Integration tests are not passing
- Switching back to the production cluster in QA to roll forward

SFR-2537: Switching back to production cluster

---

managers/oclc_catalog.py

Updates the OCLC catalog API params to narrow down results only to include digital books.
Reasoning for replacing `itemType` with `itemSubType`:
When both `itemType` and `itemSubType` parameters are provided in the query, the `itemType` will take precedence and limit the results based on the top-level facet type (book). As a result, the `itemSubType` will not affect the results, as it is overridden by the `itemType`. The `itemSubType` of 'book-digital' refines the results within the 'book' category.
This reduced the results of the API call in the `test_frbr_process.py` catalog process test from 8 records to 3.
make functional

SFR-2533: Update oclc cat api param to narrow results

---

managers/kMeans.py

- Some records, such as Gutenberg, will only have the issued date. 
- This change adds the issued date when determining the publication date during clustering.

SFR-2539: Adding issued date when determining publication date

---

api/blueprints/drbCollection.py
config/qa.yaml
managers/oclc_catalog.py
tests/conftest.py
tests/functional/processes/frbr/test_frbr_process.py
tests/functional/processes/ingest/test_nypl_process.py
tests/integration/test_oclc_catalog_manager.py

- We are going to try to migrate to the new QA cluster today
- Adding some logging to see if we are closing db sessions properly when querying for collections
- Started the API against the QA cluster locally - looks good!

SFR-2537: Migrating to new QA cluster

---

processes/ingest/gutenberg.py
services/sources/gutenberg_service.py

- The rate limit headers are sometimes not present, so defaulting to 1 request left and request at to 1 hour in the future
- Also allowing for us to handle records that don't have any yaml text files to add the cover
`python main.py -p GutenbergProcess -e local -i complete -l 100`

SFR-2525: Fix Gutenberg rate limit setting

---

processes/ingest/publisher_backlist.py
services/sources/publisher_backlist_service.py
tests/unit/processes/ingest/test_pub_backlist_process.py

- Removes the CoreProcess
- Uses record buffer
- Removes full import field and instead relies on start_datetime!
`make unit`

NO-REF: Removing CoreProcess from PublisherBacklistProcess

---

processes/record_clusterer.py
processes/record_pipeline.py

- Previous sessions were causing issues with subsequent db transactions. 
- Ensures that we rollback the changes if we fail to commit 
- Creates a new session per message and closes that session after
- Disposes the db engine after processing all messages 

SFR-2562: Creating separate session for each record pipeline message

---

processes/record_clusterer.py
processes/record_pipeline.py

- Fixes issue where the record fails to cluster due to stale data.
- Both `_create_work_from_editions` and `_delete_stale_works` may modify the same rows in the `Editons` or `Works` tables, so we need to commit after each transaction

SFR-2563: Fix db mismatch issue

---

scripts/report_missing_files.py

- Checks the head of files at a URI outside of S3
- Adds parallel processing
- Pulls record parts into memory - the session is not pickleable 
```
python main.py --script ReportMissingFiles -e local-qa options source=nypl
nypl records with missing files: 1/20489 - total: 1031136
```

NO-REF: Improve report missing files script

---

.gitignore
README.md

1. Gitignoring local `mise.local.toml` file which I use to manage local tool versions (specifically to install the right python version for this project): https://mise.jdx.dev/
2. Adding readme steps to set up python properly

Update gitignore and README

---

services/sources/gutenberg_service.py

- There's a small Gutenberg service limit comparison bug when the limit is not set
- Just adding a check beforehand

NO-REF: Fixing Gutenberg service limit comparison bug

---

api/utils.py
config/local.yaml
mappings/publisher_backlist.py
services/sources/publisher_backlist_service.py

- Implements Schomburg ingest 
- Adds pdf url from pdf pipeline bucket if there is a Hathi ID
- TODO - make sure files are moved over to the drb-files buckets and make sure they are publicly accessible 
- Marked a record as ready to ingest in Airtable: https://airtable.com/appBoLf4lMofecGPU/tblXzsYyX9ZNrmP0H/viwifoeLgCJgZWzUu?blocks=hide
`python main.py -p PublisherBacklistProcess -e local`
`python main.py -p RedriveRecordsProcess -e local`
`python main.py -p RecordPipelineProcess -e local`
- Ensured that the record was properly clustered and available on frontend:

NO-REF: Implement Schomburg ingest

---

services/sources/publisher_backlist_service.py

This hotfix PR adds the 'ACL' argument to allow the SCH pdfs to be publicly accessible in the DRB S3 titles bucket.

NO-REF--Make Schomburg PDFs Public in S3

---

.github/workflows/vercel-preview.yml

- When web code is changed and a PR is created, it's oftentimes useful to generate a preview deployment with Vercel so that devs, qa, designers, and product folks can do review on these links.
- This was previously configured via Vercel/Git integration in https://github.com/NYPL/sfr-bookfinder-front-end but now that we've moved the web code to this repo, we need to configure it here
- We're doing this using GH Actions instead of the Vercel/Git integration because this allows us to use a personal VERCEL_TOKEN (in this case, @samanthaandrews' token) which means all Preview deployments will build, even if someone without a paid Vercel seat makes changes to the code

Configure Vercel preview deployments in GH Actions

---

etl-pipeline/managers/pdf_cover_generator.py
etl-pipeline/requirements.txt
etl-pipeline/services/sources/publisher_backlist_service.py

Add a simple class that takes a stream of PDF data and generates a cover image, and use it in the publisher_backlist ingest to extract and store covers in S3, and add a has_part entry to the record that later gets attached to the edition during clustering.  See commits for some more detail
https://newyorkpubliclibrary.atlassian.net/browse/SFR-2559
Download a Schomburg PDF from the drb-files-qa bucket (in this example, hvd.32044041891367.pdf) and then upload it to localstack:
```
$ aws s3 cp ~/Downloads/hvd.32044041891367.pdf s3://drb-files-local/titles/publisher_backlist/Schomburg/hvd.32044041891367/hvd.32044041891367.pdf --endpoint-url=http://localhost:4566
```
Run the publisher backlist process:
```
$ python -m main -p PublisherBacklistProcess -e local -i complete
```
Run the classify …

Generate covers during publisher backlist ingest

---

etl-pipeline/api/blueprints/drbCollection.py
etl-pipeline/tests/unit/test_api_collection_blueprint.py

- Since the frontend doesn't necessarily use the publications in the OPDS2 feed on the home page, we want to skip building the publications
- The collections query itself doesn't take too long but building out the publications does take a while
- The GET collections endpoint given a uuid will still build the publications and takes a long time, so we should still shoot to improve performance
`npm run dev; python main.py -m APIProcess -e local-qa

NO-REF: Fix collections load time

---

etl-pipeline/api/blueprints/drbCollection.py
etl-pipeline/api/db.py
etl-pipeline/model/__init__.py
etl-pipeline/tests/unit/test_api_collection_blueprint.py
etl-pipeline/tests/unit/test_api_db.py

We've been fetching the collection and then later filtering with pagination params. My previous PR to eager load works and identifiers kinda made things worse, in that it led to us eager loading data for every edition, not just the filtered ones.
So, pass the pagination params into the DB method, first fetch the page of editions and then attach them to the collection object.
Id tried to do this using the orm loading strategies but couldn't really get it working, so I figured, just doing two pretty small quorm loading strategies but couldn't really get it working, so I figured, just doing two pretty small queries is fine and probably easier to understand.
Hit the collections/{uuid} endpoint locally

fix: Paginate collection OPDS pubications

---

etl-pipeline/managers/muse.py

- Muse looks to switch from span to h3 and from li elements to divs
- Adds a fallback for these elements just in case
`make up; make functional`

NO-REF: Fix muse chapter table card scrape

---

etl-pipeline/scripts/add_covers_to_schomburg_editions.py

There's some order of operation issues wrt the Schomburg ingest and the covers - since the ingest was done before the cover stuff was added to it, the editions didn't get cover images and becaue of the non-determinism of the clustering, I don't want to re-run the ingest, as it will affect the number of editions / clusters in the collection.
So instead, just add the covers directly onto the images.
https://newyorkpubliclibrary.atlassian.net/browse/SFR-2559
Ran this against QA and loaded a Schomburg edition: https://drb-qa.nypl.org/edition/7076343

Directly add covers to Schomburg editions

---

web/src/components/CollectionItemCard/CollectionItemCard.test.tsx
web/src/components/CollectionItemCard/CollectionItemCard.tsx
web/src/util/CollectionUtils.tsx

Was testing some of the server side cover work I did and noticed I could get covers to load for an individual edition but not on the collection page - inspected the components and looks like we were trying to pass an OpdsPublication to a cover method that expects a full feed. Easy enough to just write a new cover finding method for a single edition.
https://newyorkpubliclibrary.atlassian.net/browse/SFR-2559
Ran locally against the QA API and took a look at the Schomburg collection, saw that the covers are now loaded:

fix: Properly load covers on collection page

---

.github/workflows/etl-pipeline-deploy-qa.yaml

Something I noticed the other day - we tell ECS to deploy the new image and then immediately run integration tests. However, with how ECS deployments work, it's not clear whether the tests are hitting the old or new tasks. Waiting for services to be stable will ensure we're testing against the new image and will also avoid running the tests if the new instance never becomes healthy

Finish QA deploy before integration tests run

---

etl-pipeline/README.md
etl-pipeline/main.py
etl-pipeline/managers/s3.py
etl-pipeline/model/postgres/record.py
etl-pipeline/processes/link_fulfiller.py
etl-pipeline/processes/util/redrive_records.py
etl-pipeline/services/sources/publisher_backlist_service.py
etl-pipeline/tests/conftest.py
etl-pipeline/tests/functional/processes/test_link_fulfiller.py

- Fixes saving filed to limited bucket which does not allow ACLs 
- Fixes using local-qa/local-production config where environment is set in the config
- Changes limited_access flag to fulfill_limited_access
- Updates redrive process
- Fixes publisher backlist ingest for records that do not have a hathi_id
`make up; make functional; make integration`

SFR-2619: Fix publisher backlist ingest process

---

.github/workflows/etl-pipeline-deploy-qa.yaml

Sigh, *something* is preventing this from working, maybe some kind of memory issue that makes ECS take forever to come alive?  I created https://newyorkpubliclibrary.atlassian.net/browse/SFR-2634 to investigate further.

Remove ecs wait step from deploy

---

etl-pipeline/processes/__init__.py
etl-pipeline/processes/record_deleter.py
etl-pipeline/processes/record_pipeline.py
etl-pipeline/services/sources/publisher_backlist_service.py

- Moves the deletion logic from publisher backlist ingest to a record deleter
- The record deleter delete_record function is called when the deletion flag on a record is true
- Still need to add a test
- Will add the deleted record retrieval back in after migrating out the rest of the logic 
`make up; make functional; make integration`

SFR-2619: Extract deletion logic from publisher backlist ingest

---

etl-pipeline/processes/ingest/chicago_isac.py
etl-pipeline/processes/ingest/clacso.py
etl-pipeline/processes/ingest/hathi_trust.py
etl-pipeline/processes/ingest/met.py
etl-pipeline/processes/ingest/nypl.py
etl-pipeline/processes/record_ingestor.py
etl-pipeline/tests/functional/processes/frbr/test_record_pipeline.py

Some ingests have custom manifest logic, and future ingest processes might have more custom processing. So decouple the source service from the ingestor, instead simply passing a (usually lazy) collection of records to the ingestor, allowing the ingest process to do any special processing of records before handing them off to the ingestor.
For now, the changes in this PR are boilerplate, since we haven't transitioned any of the special ingests to the record ingestor

Decouple RecordIngestor from SourceService

---

etl-pipeline/docker-compose.setup.yml
etl-pipeline/services/sources/hathi_trust_service.py

- Introduces a healthcheck to the RabbitMQ container in the `docker-compose.setup.yml` and then uses that to make sure that RabbitMQ is ready before running the `drb_local_seed` container by depending on the health check. 
- Increases the HathiTrust TSV field size limit by 8x since I was getting errors about hitting the limit while seeding my DB. A slightly lower limit may work, but I also tried 4x and that didn't work. 
- Run the setup process using `docker compose -f docker-compose.setup.yml up --abort-on-container-exit` and ensure the seed completes without errors. You might try wiping local data before doing that so you can be sure it actually added data

Fix: local seed script

---

etl-pipeline/api/blueprints/drbCollection.py
etl-pipeline/config/production.yaml
etl-pipeline/config/qa.yaml
etl-pipeline/processes/api.py

The API *generally* doesn't write data to the DB, so point it at the read replica so that things run smoothly if data ingests are doing a lot of writes.
https://newyorkpubliclibrary.atlassian.net/browse/SFR-2666
`python -m main -p APIProcess -e local-{qa|production}` and hit localhost:5050

Use read replica for API

---

etl-pipeline/api/app.py
etl-pipeline/api/db.py
etl-pipeline/config/local-compose.yaml
etl-pipeline/config/local.yaml
etl-pipeline/tests/unit/test_api_app.py

- Fixes the env issues with running on local-qa or local-production
- You'll need to add STAGE: development to those files if you want to run the API locally but against qa or production
`python main.py -p APIProcess -e local-qa`

NO-REF: Reduce API task memory

---

etl-pipeline/managers/sqs.py
etl-pipeline/processes/record_ingestor.py
etl-pipeline/tests/integration/test_sqs.py
etl-pipeline/tests/unit/test_sqs.py

To do a final check that the queue is configured properly in AWS, start
writing messages to SQS, so we can validate they can be written and the
message format is as expected. Once this is validated, we can purge the
queue, update the record pipeline to read from the queue, and remove the
RabbitMQ step
Run `make functional`, then observe the messages in the queue in the localstack UI

Write record ingest messages to SQS

---

etl-pipeline/migrations/versions/eb6ce7780436_add_record_state.py
etl-pipeline/model/postgres/record.py

This column will eventually supplant cluster_status and frbr_status, and the new ingested state will allow us to persist records during ingested to reduce SQS payload size
`alembic upgrade head`, look at DB

Add `state` column to record table

---

etl-pipeline/mappings/oclcCatalog.py
etl-pipeline/mappings/oclc_bib.py
etl-pipeline/migrations/versions/eb6ce7780436_add_record_state.py
etl-pipeline/model/__init__.py
etl-pipeline/model/postgres/record.py
etl-pipeline/processes/record_buffer.py
etl-pipeline/processes/record_clusterer.py
etl-pipeline/processes/record_embellisher.py
etl-pipeline/processes/record_file_saver.py
etl-pipeline/processes/record_ingestor.py
etl-pipeline/processes/record_pipeline.py
etl-pipeline/processes/util/redrive_records.py
etl-pipeline/tests/functional/processes/frbr/test_cluster_process.py
etl-pipeline/tests/functional/processes/frbr/test_embellish_process.py
etl-pipeline/tests/functional/processes/frbr/test_record_pipeline.py

when ingesting records, persist them with a new `state` value of `ingested`, and then send a smaller message to SQS, just containing the record id to stay under the SQS message size limit.
Note, I adapted the record buffer a bit here so that the ingestor could consume the buffered records as they get flushed out - I *could* instead replicate / extract the upsert logic in the record buffer into the ingestor, but this way was fastest.
Run the loc ingest `python -m main -p LOCProcess -i complete -l 5`, observe the new records in the DB with the correct state, and the new messages in localstack SQS

SFR-2678: Persist records and set state in ingestor

---

etl-pipeline/managers/sqs.py

In practice doesn't break anything since we always pass something in, but breaks the integration test, since boto3 frustratingly doesn't like an explicitly set `None`

fix: Handle null SQS visibility timeout

---

etl-pipeline/tests/functional/processes/ingest/test_gutenberg_process.py

I'm gonna try to do a more robust thing later to mock out the service with some known set of records, but this should do the thing in the meantime!

fix: Handle missing gutenberg files in test

---

etl-pipeline/processes/candidate_record_finder.py
etl-pipeline/tests/conftest.py
etl-pipeline/tests/fixtures/generate_test_data.py

- We should only try to create candidate records if the state is past the ingestion step
`make functional; make integration`

NO-REF: Add record state filter when generating candidate pool

---

etl-pipeline/managers/kMeans.py
etl-pipeline/tests/unit/test_kmeans_manager.py

- 99% of records do not have an edition statement (_has_version) 
- As such, let's remove the edition statement from the kmeans pipeline to see if it helps with performance 
`make unit; make functional; make integration`

NO-REF: Remove edition statement from kmeans pipeline

---

etl-pipeline/managers/kMeans.py
etl-pipeline/parsers/__init__.py
etl-pipeline/parsers/date_parser.py
etl-pipeline/parsers/year_parser.py
etl-pipeline/tests/unit/test_kmeans_manager.py
etl-pipeline/tests/unit/test_year_parser.py

- First of a few passes to move out clean up the kmeans logic\
- Moves out the year and date parsing logic to separate files/classes
`make unit`

NO-REF: First pass - move out extraneous kmeans logic

---

etl-pipeline/services/grin/conversion.py
etl-pipeline/services/grin/grin_client.py
etl-pipeline/services/grin/util.py

This PR adds converting a batch of backfilled books to the daily conversion script. Specifically, it grabs a batch of relevant backfilled books, kicks off conversion for those, and updates the records in the database.
You can test this by having some barcodes that are pending_conversion in your DB with a date of 8-24-1991. Comment out line 26 and 28 to isolate the backfill functionality. Run the file and you can check that conversion is kicked off in GRIN for those barcodes and the DB has been updated accordingly.

SFR-2702 Initiate conversion for backfilled books

---

etl-pipeline/services/grin/conversion.py
etl-pipeline/services/grin/grin_client.py

The converted API returns a list of barcodes with file extension, we need to strip that since we only store the barcodes from our other processes

NO-REF: Remove file extension

---

etl-pipeline/scripts/GRIN_initial_scrape.py
etl-pipeline/services/grin/conversion.py
etl-pipeline/services/grin/download.py

The GRIN initial scrape script grabs all of the barcodes that exist in GRIN and inserts them into the DB. Upon testing locally, I found that the script failed when a record with the same barcode already exists in the DB - instead, we want it to just skip over that barcode and continue inserting. This PR adds logic for that as well as cleans up the scrape script to use the GrinClient and makes the batch size an argument, so that we can configure this more easily. Because we'd like to insert a smaller subset of books in QA and Prod, I added a break in the loop to finish after one batch of books (will remove this when we want to run the script in its entirety).
Lastly, I made the batch size configurable as a command line argument in the conversion and download script as well. 
Run `python3 …

GRIN initial scrape script update

---

etl-pipeline/processes/grin/conversion.py
etl-pipeline/processes/grin/grin_client.py

When running the GRIN conversion yesterday, we ran into some timeouts because the batch size for conversion was too large. This PR reduces the batch size (I ran it locally on an overall set of 1000 books and it didn't time out this time) and also adds some additional updates for the potential conversion response.

Reduce batch size for GRIN conversion

---

etl-pipeline/managers/nypl_api.py
etl-pipeline/processes/grin/conversion.py
etl-pipeline/processes/grin/download.py

This PR kicks off the file conversion step function after a book is downloaded and extracted from GRIN. It also adds the file conversion kick off to the NYPL API Manager to keep the API code together.
This PR also takes care of a small GRIN conversion edge case where books that were updated as converted but not yet in our DB would be passed over.
`python3 -m processes.grin.download --barcode=33433115534533` (This is a new barcode extracted and uploaded to our QA bucket)

Kick off file conversion after GRIN download

---

etl-pipeline/docker-compose.setup.yml

Removes rabbitmq from the docker-compose.setup.yml since it is no longer used.
Set up the ETL pipeline locally 
`docker compose -f docker-compose.setup.yml up --abort-on-container-exit`

Remove rabbitmq from docker-compose setup

---

.github/workflows/playwright.yml

- Since these tests run on every PR and after QA deployments, the Slack notification to the `#test-reports` channel is not useful. Instead, failures are reported on PRs and emails sent to the engineer who pushed the code.

Remove slack playwright notification

---

etl-pipeline/processes/pdf_generation/pdf_generate.py

- Files are always unpacked in the private bucket :) 
- tested locally

Hotfix: Always use private bucket for pdf page generation

---

etl-pipeline/processes/grin/download.py
etl-pipeline/processes/grin/grin_client.py
etl-pipeline/tests/functional/processes/grin/download_test.py

- Streams tar files from GRIN to reduce memory usage
- Uses temp files to store OCR packages on disk
- Streams to S3
`pytest tests/functional/processes/grin/download_test.py -s -vv `

[SCHOL-66] Reduce memory usage in GRIN download

---

etl-pipeline/processes/grin/conversion.py

This PR does the following for the GRIN conversion script:
- Increases the default conversion batch limit to 5000
- Removes SQS message send entirely
- Removes limiting in the backfill query, so all of the books that are pending conversion in the DB will be kicked off for conversion and batch by batch, will be updated in the DB.

Grin conversion optimizations

---

etl-pipeline/processes/grin/download.py
etl-pipeline/tests/functional/processes/grin/download_test.py

This PR updates the GRIN ingestion to only upload the METs file in the unpacked TAR file. This change is to speed up ingestion.
I tested this in QA (see here: https://us-east-1.console.aws.amazon.com/s3/buckets/drb-files-limited-qa?region=us-east-1&bucketType=general&prefix=grin/33433124453139/&showversions=false). You can use the same barcode, change the grin state in the DB to converted, and run the GRINIngestProcess on the barcode.

GRIN Ingestion only upload METs

---

etl-pipeline/processes/grin/conversion.py

- Uses in process count to avoid rate limits from GRIN
- send converted messages to download
~please don't test~
`python main.py -p GRINConversion -e local-production -i complete`

[NO-REF] Use in process count to avoid rate limits

---

etl-pipeline/mappings/hathitrust.py
etl-pipeline/tests/unit/mappings/test_hathitrust_mapping.py

- HathiTrust is now blocking us from downloading their PDFs
- Switches back to using links instead of storing files within S3

[NO-REF] Switch back to not save HathiTrust files

---

etl-pipeline/README.md
etl-pipeline/processes/grin/conversion.py

This branch contains a few updates I came across while working on running GRIN processes locally. Wanted to put them up as part of getting ready to onboard new folks
1) Call out the need for `gpg` to be installed locally for GRIN decryption
2) Fixed a bug in the conversion process that caused a crash if no failed barcodes were avialble to retry
3) Fixed a bug that caused new barcodes to be skipped if no barcodes were available to be updated in the converted books method

NOREF Updates based on local development

---

etl-pipeline/api/blueprints/item_read.py
etl-pipeline/processes/grin/unpack.py
etl-pipeline/tests/unit/grin/test_unpack.py

[SCHOL-120](https://newyorkpubliclibrary.atlassian.net/browse/SCHOL-120)
Branched from vra-jamz
- Adds GRINUnpackService that is called from the `/item/{item_id}/read/{page_id}` endpoint when the files have not been unpacked and uploaded to S3
Future considerations:
- Each time the next page is loaded, the tar file needs to be downloaded and unpacked. We should look into caching the files for the session or a set time period.
Speed demo from my local-qa env
https://github.com/user-attachments/assets/cd4a0b46-5be6-4ff7-9ccc-1aa1cf503d0a
The barcode (33433008478368) linked to the item tested above is in `drb-files-limited-qa` as an unpacked tar file.
[SCHOL-120]: https://newyorkpubliclibrary.atlassian.net/browse/SCHOL-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

SCHOL-120: Add unpacking service for web reader
