NYPL/digital-research-books

- CHANGELOG.md
- managers/kMeans.py
- managers/s3.py
- managers/sfrRecord.py
- mappings/gutenberg.py
- mappings/hathitrust.py
- mappings/oclcCatalog.py
- model/postgres/edition.py
- model/postgres/item.py
- model/postgres/link.py
- model/postgres/record.py
- processes/sfrCluster.py
- requirements.txt
- tests/unit/test_hathitrust_mapping.py
- tests/unit/test_kmeans_manager.py
- tests/unit/test_s3_manager.py
- tests/unit/test_sfrCluster_process.py
- tests/unit/test_sfrRecord_manager.py
This commit includes the following updates:
- Resolves issue where the `OCLCCatalog` process was producing bad `link` strings
- Updates the `ClusterProcess` to understand which columns have data and use those in the ML model
- Improves other data parsing aspects to reflect new NYPL data being ingested
- Resolves bug in db update call to mark records as processed
- Additional edge case handling
> NOREF clustering improvements and bugfixes

- CHANGELOG.md
- managers/kMeans.py
- managers/oclcClassify.py
- Handle unexpected byte error in language code/name parsing
- Handle unkexpected number of elements in date parsing during clustering
> NOREF Bugfixes

- CHANGELOG.md
- api/blueprints/drbSearch.py
- api/utils.py
- managers/redis.py
- managers/sfrRecord.py
- mappings/gutenberg.py
- mappings/hathitrust.py
- mappings/muse.py
- model/postgres/rights.py
- tests/unit/test_api_search_blueprint.py
- tests/unit/test_api_utils.py
- tests/unit/test_hathitrust_mapping.py
- tests/unit/test_sfrRecord_manager.py
This branch implements a number of minor changes that have come out of testing and integration with the DRB front-end client. These improvements are:
- Minor fix to limit of Catalog queries made
- Improved paging object that provides better context to API search result
- Improved rights object in API response (with improved data in background)
- Improved subject and entity name matching/de-duplication
- Trailing punctuation removal from work titles
> NOREF 20210326 API Updates

- CHANGELOG.md
- api/app.py
- managers/coverFetchers/googleBooksFetcher.py
- managers/db.py
- processes/oclcClassify.py
- tests/unit/test_db_manager.py
- tests/unit/test_fetcher_googlebooks.py
- tests/unit/test_oclcClassify_process.py
This commits a number of bugfixes for the ingest process:
- Handle deadlock errors in PostgreSQL
- Return clean `400` error for invalid query parameter options
- Catch edge case errors in Google Books Fetcher
> NOREF Daily Bugfix Commit

- .github/workflows/tests-regression.yaml
- .gitignore
- CHANGELOG.md
- Makefile
Allure results were not displaying due to pathing issues. This patch resolves this issue.
> Refactor Allure GitHub Workflow

- api/blueprints/drbCollection.py
- requirements.txt
Sometimes headers have lower case keys, a situation that needs to standardized. This regularizes the header keys to this value with should increase stability
> SFR-1246 Handle lower case header values

- CHANGELOG.md
- api/app.py
- api/blueprints/drbOPDS2.py
- api/utils.py
- managers/elasticsearch.py
- mappings/oclcCatalog.py
- processes/sfrCluster.py
- tests/unit/test_api_app.py
- tests/unit/test_api_es.py
- tests/unit/test_api_opds_blueprint.py
- tests/unit/test_oclcCatalog_mapping.py
- tests/unit/test_sfrCluster_process.py
This implements a number of small improvements to the processing of records and the serving of the API:
- This sets the default scheme for the waitress WSGI server to `https` which improves compatibility with SwaggerUI
- The parsing of InternetArchive links is updated to better capture copyright status
- The clustering approach is strengthened to be more aggressive about clustering records together
> NOREF General Stability Improvements

- .github/workflows/tests-regression.yaml
- CHANGELOG.md
- README.md
- managers/db.py
- managers/elasticsearch.py
- managers/oclcClassify.py
- managers/redis.py
- managers/sfrElasticRecord.py
- managers/sfrRecord.py
- processes/developmentSetup.py
- processes/oclcClassify.py
- processes/sfrCluster.py
- tests/unit/test_db_manager.py
- tests/unit/test_developmentSetup_process.py
- tests/unit/test_es_manager.py
- tests/unit/test_oclcClassify_manager.py
- tests/unit/test_oclcClassify_process.py
- tests/unit/test_redis_manager.py
- tests/unit/test_sfrCluster_process.py
- tests/unit/test_sfrElastic_manager.py
- tests/unit/test_sfrRecord_manager.py
This contains a range of improvements to the DRB ETL pipeline. Included in this are:
- Stability improvements for the clustering process by implementing an ES indexing solution that avoids the persistent `409 Conflict Error` issues that have been encountered. These also have the side effect of improving the speed of indexing by batching ES writes
- Performance improvements to the OCLC Classification process. This also contains a batch writing update, in this case to the RabbitMQ service
- Update/refresh of the development setup script
- Other improvements
- Testing updates
> NOREF Clustering Stability and Performance Improvements

- CHANGELOG.md
- api/utils.py
- tests/unit/test_api_es.py
The links I attached to the readable, downloadable, and requestable keys are just random for right now since I'm not sure which links should be associated with each key. I think we should ask Jackie and Crystal which media types and links should be considered readable, downloadable, and requestable.
> Updated format dictionary in APIUtils class

- CHANGELOG.md
- api/utils.py
- managers/parsers/inTechOpenParser.py
- scripts/__init__.py
- scripts/updateOldInTechOpenLinks.py
- tests/unit/test_api_utils.py
I decided to expose the entire author object instead of just the name and viaf properties.
> Sfr 921v2 work author object

- scripts/updateESEditionFormats.py
This adds some error handling and edge-case guarding to make the script more robust. Specifically this:
1. Handles an ES `NotFoundError` in the case a work cannot be located
2. Skips any incorrectly identified editions (generally occurs in the case of duplicate works).
> SFR-1498 Update script to be more robust

- migrations/versions/9e33fa16ba82_add_gin_index_to_edition_measurements.py
- model/postgres/edition.py
- scripts/govDocES.py
This improves the query in two ways:
* Eliminates unecessary data returns by limiting the query to returning uuid and measurement fields
* Reduces number of rows returned by aggregating all edition measurements with a single uuid for a work
> WIP SFR-1510 Make query for edition measurements more effecient

- CHANGELOG.md
- scripts/__init__.py
- scripts/deleteElasticRecords.py
- scripts/deleteStartStrings.py
- scripts/extractAllEditions.py
- scripts/interstitialPagesSFR1410.py
- scripts/updateESEditionFormats.py
- scripts/updateLinksCatalog.py
- scripts/updateOldInTechOpenLinks.py
- scripts/updateRecordsCatalogLink.py
I used the `govDocES` script as a basis for this script and the only question I have is how to iterate through the ESC works because I just put `esManager` instead of `dbManager` in front of the `session.query` code line for now.
> New script to delete ESC works not in Postgresql

- .gitignore
- CHANGELOG.md
- Dockerfile
- Makefile
- README.md
- api/app.py
- config/sample-compose.yaml
- docker-compose.yml
- processes/developmentSetup.py
- scripts/deleteElasticRecords.py
- tests/unit/test_developmentSetup_process.py
The purpose of adding a Docker Compose file is to allow current and future backend engineers an easy set up for a local development environment. The issue at the moment is a ConnectionError with the ElasticSearch dependency for the devsetup container. With this issue, the root causes might be that the ES container hasn't finished setting up before the devsetup container's command runs or there might be a typo in the ES credentials in the config file.
> Added DockerCompose file

- CHANGELOG.md
- managers/elasticsearch.py
- tests/unit/test_es_manager.py
I added a if/else conditional for the cases where there is a single or multiple hosts for ES.
> Sfr 1539 multi host es

- CHANGELOG.md
- api/opds2/publication.py
- scripts/deleteElasticRecords.py
- scripts/extractAllEditions.py
- scripts/govDocES.py
- scripts/updateESEditionFormats.py
- scripts/updateLinksCatalog.py
- scripts/updateOldInTechOpenLinks.py
- scripts/updateRecordsCatalogLink.py
- tests/unit/test_opds_publication.py
I created this new PR because the old one got merged accidentally into main before we completed it.
> SFR-1543v2: Read Online Link in Publication Class

- .gitignore
- CHANGELOG.md
Add a couple things:
1. Temporary swp files generated by vim on an open file
2. `tags` file generated by ctags for indexing objects in code
> Add a couple gitignore entries

- CHANGELOG.md
- main.py
- managers/oclcClassify.py
See individual commit messages
https://jira.nypl.org/browse/SFR-1603
> Handle oclc connect timeout and set nr agent timeout

- CHANGELOG.md
- config/sample-compose.yaml
Had to set this variable to make some of the endpoints in my webapp docker container, seems good to make sure it works for everyone!
> Add DEFAULT_COVER_URL to local-compose env

- api/db.py
See commit messages, first one does a basic filter (in lieu of a potential future per enhancement that's more robust) and the second one fixes some deduping issues (see the commit message for details).
https://jira.nypl.org/browse/SFR-1584
> Fix preferred editions query

- CHANGELOG.md
- api/blueprints/drbCollection.py
- swagger.v4.json
- tests/unit/test_api_collection_blueprint.py
This PR adds the ability to add one or more editions/works to a collection currently in the database. I've also included conditionals to avoid adding duplicate or nonexistent editions/works.
> SFR-1616: Add work/edition as request parameters to update collections

- CHANGELOG.md
- model/postgres/edition.py
- model/postgres/work.py
- scripts/__init__.py
- scripts/deleteDuplicateAgents.py
This script intends to delete the current duplicate work authors, work contributors and edition contributors with modified regular expressions and levenshtein score.
> SFR-1647_DeleteCurrentDuplicateAgents

- CHANGELOG.md
- managers/sfrRecord.py
- scripts/deleteDuplicateAgents.py
This PR focuses on modifying the agentParser method to reduce the number of duplicate authors/contributors when future records are ingested and added to the database.
> SFR-1648_ReduceFutureDuplicateAgents

- CHANGELOG.md
- managers/oclcClassify.py
- managers/sfrRecord.py
- tests/unit/test_oclcClassify_manager.py
This PR fixes the classification error that I ran into when attempting to cluster the ISAC records.
> SFR-1697_ISACRecordClassificationError

- CHANGELOG.md
- mappings/loc.py
This PR creates a mapping for the Library of Congress Open Access and Digitized Collections that will be integrated into DRB.
> SFR-1718_LOCMapping

- CHANGELOG.md
- api/utils.py
- mappings/UofSC.py
- mappings/chicagoISAC.py
- mappings/loc.py
- processes/__init__.py
- processes/loc.py
- tests/unit/test_isac_mapping.py
- tests/unit/test_loc_mapping.py
- tests/unit/test_loc_process.py
This branch focuses on creating a process for ingesting the LOC Open Access and Digitized Book Collections. I've been able to ingest the works into the records table of my local database successfully. The only problem I've run into is attempting to store an epub manifest for the works that have epub links which results in a blocking RabbbitMQ connection error. This is why lines 29-33 and line 166 are commented out for right now.
> SFR-1717_LOCAPIProcess

- CHANGELOG.md
- mappings/loc.py
- processes/loc.py
- processes/s3Files.py
- tests/unit/test_loc_mapping.py
- tests/unit/test_loc_process.py
This PR focuses on adding automatic ingestion for the LOC items. This auto ingestion will be weekly instead of daily due to the LOC site not being as updated consistently compared to other sources in DRB.
> SFR-1718v2_AutoIngestionLOC

- CHANGELOG.md
- requirements.txt
Seeing an issue with a particular query on startup of our containers that ultimately causes them to immediately spin down.
We observed an error very closesly matching
https://github.com/sqlalchemy/sqlalchemy/discussions/9666, which looks to be caused by a race condition fixed in the newest release as of now: https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_14
Another option we might consider in the future is to make sure the `Work` objects passed into `APIUtils.formatWorkOutput` (generated from `dbClient.fetchSearchedWorks`) `joinedload`s the `Edition` objectsi so they don't have to be fetched later (check out the stack trace), but that is more likely to just be a future perf fix.
Stack trace for reference:
Traceback (most recent call last):
File …
> Upgrade sqlalchemy

- CHANGELOG.md
- mappings/UofM.py
This PR is intent out filling out the publisher_project_source field for current and future UofM books. After this is approved, I will ingest and cluster the UofM books so the current books have a non null value in this field.
> SFR-2055_PubProjectSourceUofM

- CHANGELOG.md
- README.md
This PR updates the README to clarify the steps to running the processes locally.
> SFR-2072: Local Process Steps in README

- CHANGELOG.md
> NO-REF: Release v0.13.1

- CHANGELOG.md
- api/utils.py
- This log resulted in quite a few print statements that looked like bucket []
> NO-REF: Removing aggregation result print statement

- CHANGELOG.md
- README.md
- Updating README release steps to reflect changes from last release
> SFR-2127: Update README release steps

- CHANGELOG.md
- config/sample-compose.yaml
- docker-compose.yml
- localstack/init-localstack-resources.sh
- managers/parsers/abstractParser.py
- managers/s3.py
- tests/unit/test_s3_manager.py
- This change adds a local docker container for S3 and uses localstack to create the buckets
`docker compose up` -- tested by trying to get object from S3 in dev setup script
> SFR-2073: Added local S3 docker container via localstack

- CHANGELOG.md
- api/blueprints/drbUtils.py
- tests/unit/test_api_utils_blueprint.py
- Adds error handling to each of the utils endpoints
- Added tests to ensure things are handled properly
`make test`
> SFR-2125: Adding utils API error handling

- CHANGELOG.md
- api/blueprints/drbEdition.py
- Flask param needs to match python function param name
`http://localhost:5050/edition/1`
> NO-REF: Fix edition ID API Param

- CHANGELOG.md
- analytics/upress_reporting/utils/ip_address.py
- Added function to map IP address to country
- Tested manually - looks good!
https://ipinfo.io/json
> SFR-2134: Map IP address to country

- CHANGELOG.md
- analytics/upress_reporting/counter_5_controller.py
- analytics/upress_reporting/models/aggregators/download_data_aggregator.py
- analytics/upress_reporting/models/aggregators/view_data_aggregator.py
- analytics/upress_reporting/models/data/interaction_event.py
- analytics/upress_reporting/models/reports/counter_5_report.py
- analytics/upress_reporting/models/reports/country_level.py
- analytics/upress_reporting/models/reports/downloads.py
- analytics/upress_reporting/models/reports/views.py
- This change refactors a bit of how we aggregate the data
- We aggregate the data in one place and the reports then can use the aggregated data
- Change also implements the country-level report
`python3 analytics/upress_reporting/runner.py "2024-08-01 to 2024-08-02"`
> SFR-2049: Implementing country-level analytics report

- CHANGELOG.md
- analytics/upress_reporting/counter_5_controller.py
- analytics/upress_reporting/models/reports/total_usage.py
- Implements total usage analytics report
`python3 analytics/upress_reporting/runner.py "2024-08-01 to 2024-08-02"`
> SFR-2135: Implementing total usage analytics report

- CHANGELOG.md
- api/blueprints/drbFulfill.py
- tests/unit/test_api_fulfill_blueprint.py
- refactored the fulfill API 
- added error handling :) 
`make test`
> SFR-2123: Adding fulfill API error handling

- CHANGELOG.md
- managers/oclcClassify.py
- managers/oclc_catalog.py
- mappings/oclc_bib.py
- processes/oclcClassify.py
- tests/unit/test_oclcCatalog_manager.py
- tests/unit/test_oclcClassify_manager.py
- Implements classify process using the OCLC editions endpoints
Tested by calling classify_record_by_metadata_v2 - looks good!
> SFR-2149: Implementing OCLC Classify Process with Editions Endpoints

- CHANGELOG.md
- migrations/env.py
- processes/developmentSetup.py
This change moves up the db migration process in dev setup so that it runs before trying to ingest and cluster any records.
> NO-REF: Moving up db migration in dev setup

- CHANGELOG.md
- analytics/upress_reporting/models/pollers/download_data_poller.py
- analytics/upress_reporting/models/pollers/view_data_poller.py
- analytics/upress_reporting/runner.py
- Uses editions URL as the book ID
- Pulls authors and subjects from the record instead of the work. 
- Generated [report](https://docs.google.com/spreadsheets/d/1h7-u7xI593IpBnSqo3dSgQfEmgpxsLfUouQrBwIKDwU/edit?gid=1100171918#gid=1100171918) against QA
> NO-REF: Updating book id and using record data

- CHANGELOG.md
- managers/oclc_catalog.py
- mappings/oclc_bib.py
- processes/oclcClassify.py
- tests/integration/test_oclc_catalog_manager.py
- Implements a call to query bibs from OCLC
- On of our hypotheses is that brief bibs does not provide enough information to cluster OCLC records
`make integration`
> NO-REF: Adding OCLC query bibs call

- CHANGELOG.md
- requirements.txt
- Upgrading flask and flask-cors due to security vulnerability
`make unit`
Tested API locally!
> SFR-2166: Upgrading flask-cors

- docker-compose.yml
- Upgrades Docker ElasticSearch container
- Fixes bug where polish analyzer was missing
`docker compose up; python main.py -p DevelopmentSetupProcess -e local -i complete`
> NO-REF: Ugrading Docker ElasticSearch Container

- managers/muse.py
- mappings/muse.py
- tests/unit/test_muse_manager.py
- tests/unit/test_muse_mapping.py
- Cleanup OCLC no prefix from Muse mapping
- Fixed language extraction
- Fixed ids with leading/trailing whitespace
`make unit`
> SFR-2217 Fixing MUSE Mapping

- tests/rest_api/test_get_work.py
- This ticket verifies the HTTP response for /work/{uuid}
- Verifies the JSON body is not null
> SFR-2214: get work api test

- processes/doab.py
- tests/unit/test_doab_process.py
- Improves logging and error handling
- DOAB is not ingesting e2e as of right now
> SFR-2216: Improving DOAB logging and error handling

- processes/gutenberg.py
- tests/unit/test_doab_process.py
- tests/unit/test_gutenberg_process.py
- Adding Gutenberg logging
`python main.py -p GutenbergProcess -e local -i complete -l 10`
> SFR-2216: Adding Gutenberg logging

- processes/ingest/hathi_trust.py
- Noticed that there were a lot of Read Row logs
- Improves logging and exception handling in Hathi Trust logging
`make unit`
> SFR-2284: Improve Hathi Trust logging

- tests/integration/api/test_get_collection.py
This test validates the edge cases for get/collection API
[SFR-2299](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2299)
[SFR-2299]: https://newyorkpubliclibrary.atlassian.net/browse/SFR-2299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SFR-2099: Edge Case API Tests for get/collection

- processes/file/covers.py
- processes/ingest/doab.py
- processes/ingest/gutenberg.py
- processes/ingest/loc.py
- processes/ingest/met.py
- processes/ingest/u_of_m.py
- processes/ingest/u_of_sc.py
> NO-REF: Removing redundant comments

- processes/frbr/catalog.py
- tests/unit/processes/frbr/test_catalog_process.py
- Renames OCLC Catalog Manager dependency to snake case
> NO-REF: Rename Oclc catalog manager dep

- processes/ingest/loc.py
- Fixes LOCPRoces S3 client creation
`make unit`
> NO-REF: Fix LOCProcess S3 Client

- mappings/publisher_backlist.py
- services/sources/publisher_backlist_service.py
This PR focuses on adding a few methods from the UofM ingest process to maintain that will be further developed in future PRs as progress of the Google Drive API integration continues.
> SFR-2368_PubBacklistParityWithUofM

- scripts/migrate_digital_assets.py
- A couple tweaks to the migration script
- Adds paginator to the S3 calls
- Strips IA_NYPL and batch_2 prefixes from the unprocessed file bucket 
- Creates folder in Google Drive in cases where there's a / in the S3 file key
> NO-REF: Migration script tweaks

- services/sources/publisher_backlist_service.py
This PR adds a new filter to the Airtable API to only request for records from Airtable that have a Ready to Ingest status in the Next step (from Project steps) field.
> SFR-2381: Ready to Ingest Status for Airtable Records

- managers/s3.py
- processes/ingest/chicago_isac.py
- processes/ingest/doab.py
- processes/ingest/loc.py
- processes/ingest/met.py
- services/sources/publisher_backlist_service.py
- tests/functional/processes/ingest/assert_ingested_records.py
- tests/functional/processes/ingest/test_chicago_isac_process.py
- tests/functional/processes/ingest/test_doab_process.py
- tests/functional/processes/ingest/test_gutenberg_process.py
- tests/functional/processes/ingest/test_loc_process.py
- tests/functional/processes/ingest/test_met_process.py
- tests/functional/processes/ingest/test_muse_process.py
- tests/functional/processes/ingest/test_nypl_process.py
- tests/functional/processes/ingest/test_publisher_backlist_process.py
- tests/unit/processes/ingest/test_chicago_isac_process.py
- tests/unit/processes/ingest/test_doab_process.py
- tests/unit/processes/ingest/test_loc_process.py
- tests/unit/processes/ingest/test_met_process.py
- tests/unit/processes/ingest/test_nypl_process.py
- Adds ingest process functional tests
pytest tests/functional
* Note that some tests are not passing locally - will follow up on those.
> SFR-2388: Adding ingest process functional tests

- .github/workflows/build-production.yaml
- Deploys to the new terraform stacks in production
> SFR-2397: Deploy to the new terraform stacks in production

- processes/ingest/publisher_backlist.py
- services/sources/publisher_backlist_service.py
This PR focuses on deleting Publisher Backlist record manifests and digital asset files from Google Drive. Currently there is no code for the delete_digital_asset_file method since I'm not sure where the digital assets are located on Google Drive and how to delete them with the API. Maybe @Apophenia could assist me on that?
> SFR-2391: Delete Publisher Backlist Record Manifests

- .github/workflows/build-production.yaml
- .github/workflows/build-qa.yaml
- Deploys only to the terraform stacks
- Stops deploying to the CF stacks
> SFR-2406: Deploy only to the terraform stacks

- api/app.py
- api/blueprints/__init__.py
- api/blueprints/drbEdition.py
- swagger.v4.json
- Migrates edition endpoint to use plural noun
`docker compose up and hit the endpoint /editions`
> SFR-2413: Migrate edition endpoint to use plural noun

- scripts/cleanup_duplicate_works.py
- Script deletes all duplicate works in postgres and elastic search
> SFR-2407: Cleanup duplicate works script

- managers/sfrRecord.py
- migrations/versions/0cebb9a98a6f_add_record_id_to_item.py
- model/postgres/item.py
- Adds record id to items table
- Adds cascade to delete items if record is deleted
- Does not index!
`python -m main.py -p SeedLocalDataProcess -e local`
> [SFR-2433] Adding record id to items table

- analytics/upress_reporting/counter_5_controller.py
- config/development.yaml
- config/example.yaml
- config/production.yaml
- config/qa.yaml
- config/sample-compose.yaml
- Changes the analytics script to pull from the limited files bucket logs rather than the ump files bucket logs
> SFR-2444: Updating analytics script to use new S3 log bucket paths

- analytics/upress_reporting/counter_5_controller.py
This PR focuses on aggregating download analytics from the drb-files-<env> buckets due to the new structure of our S3 buckets.
> SFR-2445: Aggregrate Download Analytics

- managers/oclc_catalog.py
- Adds defaults when parsing other editions responses
> SFR-2425: Fixing OCLC catalog response parsing

- .github/workflows/build-qa.yaml
- Made a small typo in the file type!
> NO-REF: Fix CI workflow call

- .github/workflows/ci.yaml
- .github/workflows/tests-unit.yaml
- v4 actions/cache does not work with fasttext
- also bumps python-setup to v5
- tested via adding on pull_request
> NO-REF: Reverting actions/cache to v2

- load_env.py
- services/ssm_service.py
- loads secrets when loading the env variables
`python main.py -p NYPLProcess -e local -i daily -l 15`
> SFR-2472: Load secrets when loading env

- config/example.yaml
- config/production.yaml
- config/qa.yaml
- constants/app_constants.py
- processes/file/s3_files.py
- tests/helper.py
- tests/unit/processes/file/test_s3_files_process.py
- https://epub-to-webpub.vercel.app is constants across all environments
- This change sets WEBPUB_CONVERSION_URL as a constant where it's used
> SFR-2478: Setting WEBPUB_CONVERSION_URL as a constant

- config/example.yaml
- config/production.yaml
- config/qa.yaml
- config/sample-compose.yaml
- managers/coverFetchers/hathiFetcher.py
- processes/ingest/hathi_trust.py
- processes/local_development/seed_local_data.py
- tests/helper.py
- tests/unit/processes/ingest/test_hathi_trust_process.py
- The Hathi URLs are constant across envs, as such let's make them constant!
> SFR-2478: Make Hathi urls constant

- tests/functional/processes/ingest/assert_ingested_records.py
- tests/functional/processes/ingest/test_met_process.py
- Sets up the code to test that we are able to save files for MET records
> NO-REF: Setup manifest testing for MET

- services/sources/publisher_backlist_service.py
- Separates out bugfix from larger PR
- Error logging correctly describes the action that failed
> NOREF: Fix permissions bug

- scripts/cleanup_duplicate_works.py
- Adds a couple log statements 
- Handles not found exception in elastic search
> NO-REF: Updating cleanup duplicate works script

- services/sources/nypl_bib_service.py
- tests/functional/processes/ingest/test_nypl_process.py
- Improves NYPL ingest performance by ensuring we are streaming results properly
`pytest tests/functional/processes/ingest/test_nypl_process.py -s`
> NO-REF: Improve nypl ingest performance

- processes/__init__.py
- processes/local_development/seed_test_data.py
first commit for kyle to review. 
Currently we need to add a query to create edition id and link id values for dummy test data
> SFR:2481-test_data_seed

- ingestJSONFiles/chicagoISAC_metadata.json
- mappings/chicagoISAC.py
- model/postgres/record.py
- tests/functional/processes/ingest/assert_ingested_records.py
- tests/functional/processes/ingest/assert_uploaded_manifests.py
- tests/functional/processes/ingest/test_chicago_isac_process.py
- tests/functional/processes/ingest/test_doab_process.py
- tests/functional/processes/ingest/test_gutenberg_process.py
- tests/functional/processes/ingest/test_loc_process.py
- tests/functional/processes/ingest/test_met_process.py
- tests/functional/processes/ingest/test_muse_process.py
- Tests whether we have uploading manifests during each ingest process
> NO-REF: Asserting manifests are uploaded during ingest

- services/sources/dspace_service.py
- tests/functional/processes/ingest/test_doab_process.py
Updates while loop condition to run if offset is 0
> NO-REF: Fix DOAB functional test error

- tests/functional/processes/ingest/test_doab_process.py
Remove unused imports in DOAB functional test
> NO-REF: Remove unused imports in DOAB functional test

- tests/conftest.py
- tests/integration/test_frbr_process.py
this steps does the following
- adds a test data 
- then we classify that data to verify the frbr_status in the database
> SFR-2501: Classify a record and verify the frbr status

- tests/conftest.py
- tests/functional/processes/frbr/test_frbr_process.py
this pr does the following 
- Verifies after frbrization if a classifiyCount has increased in DB
> SFR-2502/catalog_process_test

- processes/file/s3_files.py
- tests/conftest.py
- tests/functional/processes/file/test_s3_process.py
- tests/unit/processes/file/test_s3_files_process.py
- Remove CoreProcess as parent of S3Process
- Adds max_attempts param for testing
- Adds functional test
> SFR-2512: Refactor and functionally test S3Process

- mappings/clacso.py
- processes/ingest/clacso.py
This PR adds the publisher metadata from DSpace to the CLACSO mapping to allow the ClusterProcess to create editions from the CLACSO records and works.
> SFR-2515: Add Publisher to CLACSO Mapping

- mappings/clacso.py
- mappings/rights.py
- services/sources/dspace_service.py
- Parses rights from CLACSO records
- Adds mapping function to map to a rights string that other mappers can use
> SFR-2519: Parsing rights from CLACSO metadata

- scripts/__init__.py
- scripts/check_queue_size.py
- We need to be able to debug sometimes when the catalog process is taking a while to process messages
`python main.py -sc checkQueueSize -e local `
> NO-REF: Adding script to check queue size

- managers/gutenberg.py
- Fixes bug where the data in GraphQL response is not defined.
> NO-REF: Fix gutenberg bug failing to retrive rdf/yaml files

- mappings/clacso.py
- mappings/rights.py
- Fixes rights mapping to map to a single rights statement rather than a list
`python main.py -p CLACSOProcess -e local -i complete -l 5`
> NO-REF: Fix CLACSO rights mapping

- processes/frbr/classify.py
- tests/unit/processes/frbr/test_classify_process.py
- Adds the ability to filter the classify process by source
- `python main.py -p ClassifyProcess -e local -i complete -l 10 -src gutenberg`
> NO-REF: Filter classify process by source

- processes/ingest/gutenberg.py
- tests/unit/processes/ingest/test_gutenberg_process.py
- Removing core process from gutenberg ingest
- Using record buffer
`make unit; make functional`
> SFR-2525: Using record buffer in gutenberg ingest process

- Makefile
- dev-requirements.txt
- processes/frbr/classify.py
- processes/ingest/loc.py
- tests/functional/processes/ingest/test_loc_process.py
- Parallelizes tests 
- Fixes FRBR test
- Skips LOC test
`make functional; make integration`
> SFR-2538: Parallelize functional and integration tests

- model/postgres/record.py
- model/source.py
- processes/ingest/gutenberg.py
- tests/unit/processes/ingest/test_gutenberg_process.py
- Cleans up Gutenberg process
- Migrates to snake case
- Cleans up tests
`make unit`
> SFR-2525: Refactor Gutenberg Ingest Process

- services/sources/gutenberg_service.py
- We have a 5k request limit per hour per user
- Adding error handling so we can see when we get error handling
> SFR-2525: Add graphql error handling in gutenberg

- services/sources/gutenberg_service.py
- Fixing Gutenberg data file return type
> SFR-2525 Fixing Gutenberg data file return type

- mappings/doab.py
- Return single right instead of list of rights
> SFR-2524: Update DOAB mapping to return single right

- processes/record_pipeline.py
- This is just a skeleton for the record pipeline process
- I think I want to flush out the details next sprint and complete the implementation 
- Putting this PR up tho for feedback!
> NO-REF: Skeleton Record Pipeline Process

- processes/local_development/local_development_setup.py
- processes/local_development/seed_local_data.py
- Removes core process from local dev processes
`python main.py -p SeedLocalDataProcess -e local; python main.py -p LocalDevelopmentSetupProcess -e local`
> NO-REF: remove core process from local dev processes

- processes/ingest/clacso.py
- This change uses the start datetime getter util function to simplify the CLACSO ingest process
`make unit`
> NO-REF: Use start datetime logic in Clacso ingest

- processes/utils.py
- tests/unit/processes/test_utils.py
- Adding parse process args utils function
- This should remove redundant code to parse args in the processes
`make unit`
> NO-REF: Adding parse process args utils function

- managers/s3.py
- mappings/chicago_isac.py
- mappings/clacso.py
- mappings/doab.py
- mappings/loc.py
- mappings/met.py
- model/postgres/record.py
- processes/ingest/gutenberg.py
- processes/ingest/loc.py
- processes/ingest/met.py
- tests/conftest.py
- tests/functional/processes/ingest/assert_uploaded_manifests.py
- tests/functional/processes/ingest/test_gutenberg_process.py
- Coming from a predominantly java background, I'm still thinking like a java developer but I need to think like a python developer
- Uses the __str__ method to convert Part and FileFlags to a string - while this is a bit out of step with the purpose of this special method, I think it should suffice. 
- Uses @property to get the parts from a Record
> NO-REF: Make new additions more pythonic

- mappings/oclc_bib.py
- processes/__init__.py
- processes/frbr/classify.py
- processes/record_frbrizer.py
- tests/functional/processes/frbr/test_frbr_process.py
- Implements the FRBRize record step in the record pipeline process
##
> SFR-2550: Implement FRBRize record step

- processes/ingest/hathi_trust.py
- processes/local_development/seed_local_data.py
- services/__init__.py
- services/sources/hathi_trust_service.py
- tests/functional/processes/ingest/test_hathi_trust_process.py
- tests/integration/services/sources/test_hathi_trust_service.py
- Moves Hathi ingest process to use source service
- Improves performance via ingesting from multiple files at once
> NO-REF: Migrating Hathi to use source service

- .github/workflows/tests.yaml
- managers/db.py
- mappings/met.py
- processes/cluster.py
- processes/file/covers.py
- processes/frbr/classify.py
- processes/ingest/doab.py
- processes/ingest/gutenberg.py
- processes/ingest/loc.py
- processes/ingest/met.py
- processes/ingest/nypl.py
- processes/ingest/publisher_backlist.py
- processes/utils.py
- services/sources/chicago_isac_service.py
- services/sources/dspace_service.py
- services/sources/gutenberg_service.py
- services/sources/hathi_trust_service.py
- services/sources/loc_service.py
- services/sources/met_service.py
- services/sources/nypl_bib_service.py
- services/sources/publisher_backlist_service.py
- services/sources/source_service.py
- tests/unit/processes/file/test_cover_process.py
- tests/unit/processes/frbr/test_classify_process.py
- tests/unit/processes/ingest/test_doab_process.py
- tests/unit/processes/ingest/test_pub_backlist_process.py
- tests/unit/processes/test_cluster_process.py
- Moves off the core process inheritance besides MUSE, which is in a separate PR
- Refactors the processes to use the utils functions 
`make unit; make functional; make integration`
> NO-REF: Moving off of core process/refactoring to use process utils

- scripts/__init__.py
- scripts/report_missing_files.py
- Implements script ot report missing files
`python main.py --script ReportMissingFiles -e qa options source=muse`
> SFR-2572: Implementing script to report missing files

- mappings/met.py
- mappings/rights.py
- processes/ingest/met.py
- services/sources/met_service.py
- tests/functional/mappings/test_met.py
- Fixes a rights mapping error in MET that prevented clustering
- Fixes bug where we were ingesting in copyright records
- Removes cover logic since no record has a cover through the implemented method. 
`python main.py -p METProcess -e local`
> SFR-2573: Fix MET rights mapping

- managers/rabbitmq.py
- processes/file/s3_files.py
- processes/frbr/catalog.py
- processes/frbr/classify.py
- processes/ingest/doab.py
- processes/ingest/gutenberg.py
- processes/ingest/loc.py
- processes/ingest/muse.py
- processes/record_ingestor.py
- processes/record_pipeline.py
- processes/util/redrive_records.py
- scripts/check_queue_size.py
- tests/conftest.py
- tests/functional/processes/file/test_s3_process.py
- tests/functional/processes/frbr/test_record_pipeline.py
- tests/unit/processes/file/test_s3_files_process.py
- tests/unit/processes/frbr/test_catalog_process.py
- tests/unit/processes/frbr/test_classify_process.py
- tests/unit/processes/ingest/test_doab_process.py
- tests/unit/test_rabbitmq_manager.py
[SFR-2568](https://newyorkpubliclibrary.atlassian.net/browse/SFR-2568)
This primarily moves to snake case.
To test I ran `make unit`.
[SFR-2568]: https://newyorkpubliclibrary.atlassian.net/browse/SFR-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SFR-2568: Cleanup RabbitMQManager

- scripts/report_missing_files.py
- Was seeings lots of missing files - adding the user agent definitely ensures we are not getting any false positives.
> NO-REF: Adding user agent headers to missing files script

- processes/utils.py
- services/sources/gutenberg_service.py
- Adds retries to graphql queries
- Defaults to daily ingest if the ingest type is not provided
> NO-REF: Adding retries to Gutenberg graphql queries

- managers/redis.py
- processes/api.py
- processes/cluster.py
- processes/file/covers.py
- processes/frbr/classify.py
- processes/local_development/seed_local_data.py
- processes/record_frbrizer.py
- tests/functional/processes/frbr/test_frbr_process.py
- tests/unit/processes/file/test_cover_process.py
- tests/unit/processes/frbr/test_classify_process.py
- tests/unit/processes/test_api_process.py
- tests/unit/test_redis_manager.py
Convert to snake case
Add type hints
f-strings
> SFR-2569 Cleanup RedisManager

- .github/workflows/etl-pipeline-ci.yaml
- .github/workflows/etl-pipeline-deploy-production.yaml
- I missed adding `working-directory: ./etl-pipeline` in a few places
> Add working directory to pipeline ci file

- .github/workflows/etl-pipeline-ci.yaml
> Fix workflow syntax

- .github/workflows/etl-pipeline-ci.yaml
> Fix etl-pipeline-ci.yaml syntax (again)

- etl-pipeline/scripts/grin_mirror.py
- Adds the grin mirror script from gist: https://gist.github.com/Apophenia/9d76c6f703460c7fd2fb5cb7c5a3a96a
- Additional details: https://docs.google.com/document/d/1R0wTHf6ojNil-RZI8RZbzxz6M8wcQs9b7InYU84HNqw/edit?tab=t.0
N/A
> NO-REF: Adding grin mirror script

- etl-pipeline/README.md
- etl-pipeline/processes/record_clusterer.py
Simple README and code comment changes that describe my understanding of how the record clustering works as I have learned about the project
> Code comments

- etl-pipeline/scripts/__init__.py
- etl-pipeline/scripts/create_collection.py
This PR creates a script that will create a collection of all the Schomburg editions present in the DRB PSQL database.
(In the etl-pipeline folder)
- `make up`
- `python main.py -e local -sc createCollection`
> SFR-2483: Make Schomburg Collection

- etl-pipeline/managers/sfrRecord.py
- etl-pipeline/model/postgres/record.py
- etl-pipeline/scripts/report_missing_files.py
- etl-pipeline/tests/unit/test_sfrRecord_manager.py
- Adds optionally a 5th index of a has_part string which is the source_url
- Adds the ability to parse has_part strings with either 5 or 6 fields 
`make unit`
> SFR-2611: Add source_url to has_part string

- etl-pipeline/model/postgres/record.py
- etl-pipeline/processes/record_file_saver.py
- etl-pipeline/processes/record_ingestor.py
- etl-pipeline/processes/record_pipeline.py
- etl-pipeline/tests/functional/processes/frbr/test_record_pipeline.py
- etl-pipeline/tests/functional/processes/ingest/test_chicago_isac_process.py
- etl-pipeline/tests/functional/processes/ingest/test_clacso_process.py
- Sends record messages to the queue
- Adds save file step in the record pipeline process
- Adds save record step in the record pipeline process
`make up; make functional; make integration`
> SFR-2614: Add file save and record save steps to record pipeline

- etl-pipeline/processes/ingest/met.py
- etl-pipeline/tests/functional/processes/ingest/test_met_process.py
This PR adds a record ingestor to the MET ingest process to simplify the code in the process.
`make up` 
> SFR-2616: MET Record Ingestor

- etl-pipeline/model/source.py
- etl-pipeline/processes/ingest/hathi_trust.py
- etl-pipeline/tests/functional/processes/ingest/test_hathi_trust_process.py
This PR adds the record ingestor to the Hathi ingest process which simplifies the code present in the process.
`make up`
> SFR-2613: Hathi Process Record Ingestor

- .github/workflows/etl-pipeline-deploy-qa.yaml
> Fix ecs wait in qa deploy

- .github/workflows/etl-pipeline-deploy-qa.yaml
More in the saga of the bad copy paste
> Fix ecs wait

- etl-pipeline/model/source.py
- etl-pipeline/processes/ingest/nypl.py
- etl-pipeline/services/sources/nypl_bib_service.py
- etl-pipeline/tests/functional/processes/ingest/test_nypl_process.py
This PR adds a record ingestor to the NYPL ingest process to simplify the code in the process.
`make up`
> SFR-2618: NYPL Record Ingestor

- etl-pipeline/mappings/loc.py
- etl-pipeline/processes/ingest/loc.py
- etl-pipeline/tests/functional/processes/ingest/assert_uploaded_epubs.py
- etl-pipeline/tests/functional/processes/ingest/test_loc_process.py
This PR adds the record ingestor to the LOC ingest process which simplifies the code present in the process.
`make up`
> SFR-2615: LOC Record Ingestor

- etl-pipeline/processes/ingest/chicago_isac.py
- etl-pipeline/processes/ingest/clacso.py
- etl-pipeline/processes/ingest/hathi_trust.py
- etl-pipeline/processes/ingest/loc.py
- etl-pipeline/processes/ingest/met.py
- etl-pipeline/processes/ingest/nypl.py
- Removes commas after getting start_datetime
`make up; make functional; make integration`
> NO-REF: Remove commas in ingest processes

- .github/workflows/etl-pipeline-tests.yaml
- We weren't getting hits when caching which caused an extra minute per GH test run
- Fixes python dep caching
> NO-REF: Fix python req cache

- etl-pipeline/.editorconfig
See https://editorconfig.org/
I opted to just have a single file in the root dir for simplicity, but I think you can nest these. Open to either implementation
> Add an editorconfig

- .github/workflows/playwright.yml
- web/package-lock.json
- web/package.json
- web/playwright.config.ts
- Updated Playwright version
- Updated Slack notification
- Scheduled a run each weekday morning
- Updated Playwright reporter to display each test that runs for troubleshooting errors and failures
- Observe `playwright_tests` job in Web CI check
> SFR-2673: Update Playwright tests in GitHub Actions

- etl-pipeline/config/production.yaml
- etl-pipeline/config/qa.yaml
- Adds SQS names to the yaml configs
> NO-REF: Add SQS config

- etl-pipeline/managers/sqs.py
- etl-pipeline/processes/record_pipeline.py
To try to avoid conflicts between concurrent clustering jobs
> Set 90 minute vis timeout for record pipeline msgs

- etl-pipeline/tests/conftest.py
- Fixes error in the CI integration tests where there are two yields.
> NO-REF: Fix yield in fixture

- web/playwright/landing-page/landing-page.ts
- web/src/lib/newrelic/NewRelic.tsx
On the frontend I've noticed that the Nextjs server-side agent is working fine, but the client-side agent never started. This PR is to add some logs to the setup process and identify which step is causing the issue.
N/A
> NO-REF: Log NR setup steps on the client

- etl-pipeline/tests/integration/services/sources/test_dspace_service.py
- Switches DSpace urls from doab to clacso in the integration test
`make integraiton`
> NO-REF: Fix dspace integration test

- etl-pipeline/processes/__init__.py
- etl-pipeline/processes/cluster.py
- etl-pipeline/processes/file/s3_files.py
- etl-pipeline/processes/frbr/catalog.py
- etl-pipeline/processes/frbr/classify.py
- Removes deprecated processes - catalog, classify, cluster and s3 files
> SFR-2676: Remove deprecated processes

- etl-pipeline/processes/utils.py
- Setting default limit for QA since we only have one consumer
> NO-REF: Set default limit for QA

- etl-pipeline/services/sources/grin/conversion.py
Scrape the already converted books on the GRIN site and update them in the database with the `converted` state.
> SFR-2688: Add converted books

- etl-pipeline/processes/ingest/gutenberg.py
- etl-pipeline/services/sources/gutenberg_service.py
- etl-pipeline/tests/integration/services/sources/test_gutenberg_service.py
- Making change to be consistent with source services to generate records
`make integration`
> NO-REF: remove unnecessary record only var in service

- .github/workflows/etl-pipeline-full-ci-cd.yaml
- etl-pipeline/.gitignore
- deploy to prod step in GA requires both CI steps to pass
> SFR-2706: Update deploy to production needs params

- etl-pipeline/processes/record_ingestor.py
- etl-pipeline/services/monitor.py
- Adds metric to track ingest count per source
> [SCHOL-11] Add metric to track ingest count per source

- etl-pipeline/config/local.yaml
- etl-pipeline/config/production.yaml
- etl-pipeline/config/qa.yaml
- etl-pipeline/managers/s3.py
- etl-pipeline/mappings/marc_record.py
- etl-pipeline/processes/grin/download.py
- etl-pipeline/processes/grin_ingest_process.py
- etl-pipeline/processes/pdf_generation/model.py
- etl-pipeline/processes/pdf_generation/pdf_generate.py
- etl-pipeline/tests/functional/mappings/test_marc_record.py
- Refactors pdf generate to be more functional
- Moves the ingest process into pdf generate and updates it to properly process XML from metadata
- Updates bucket to be dynamically updated based on os env var
`python main.py -p GRINIngestProcess -e local` barcode needs to manually replaced
`python main.py -p RecordPipelineProcess -e local`
> [SCHOL-44] Make pdf generate functional and move ingest process

- etl-pipeline/config/sample-compose.yaml
- etl-pipeline/docker-compose.setup.yml
- etl-pipeline/docker-compose.yml
- etl-pipeline/localstack/init-localstack-resources.sh
- Adds a local grin queue
- Changes docker container name for localstack to encompass all local aws services that add
`docker compose up`
> [SCHOL-63] Add local grin queue

- etl-pipeline/config/local-compose.yaml
- Changes s3 endpoint url in local-compose
> [SCHOL-63] Change s3 endpoint url

- etl-pipeline/processes/pdf_generation/pdf_generate.py
- etl-pipeline/services/monitor.py
- Tracks pdf generation time
- Adds function decorator to record metric and log
> [SCHOL-64] Track pdf generation time

- etl-pipeline/api/app.py
- etl-pipeline/api/auth.py
- etl-pipeline/api/blueprints/__init__.py
- etl-pipeline/api/blueprints/drb_chats.py
- etl-pipeline/api/elastic.py
- etl-pipeline/api/research_assistant.py
- etl-pipeline/load_env.py
- etl-pipeline/processes/__init__.py
- etl-pipeline/processes/research_assistant_chatbot.py
- etl-pipeline/requirements.txt
- Adds a VRA chat endpoint
- Implements a simple VRA with a search tool
> [NO-REF] VRA chat endpoint

- etl-pipeline/README.md
- web/README.md
I updated the READMEs for the web and etl-pipeline
Proofread READMEs for styling issues, typos, and clarity of context
> Updated Readmes

- .github/workflows/web-deploy-qa.yml
- etl-pipeline/api/blueprints/drb_chats.py
- etl-pipeline/api/elastic.py
- etl-pipeline/api/research_assistant.py
- web/config/appConfig.ts
- web/jest.config.ts
- web/package-lock.json
- web/package.json
- web/src/components/ResearchAssistant/MessageBubble.tsx
- web/src/components/ResearchAssistant/ResearchAssistant.test.tsx
- web/src/components/ResearchAssistant/ResearchAssistant.tsx
- web/src/components/ResearchAssistant/ResearchAssistantInput.tsx
- web/src/components/ResearchAssistant/ResearchAssistantWindow.tsx
- web/src/components/ResearchAssistant/useResearchAssistant.tsx
- web/src/pages/api/research-assistant.ts
- web/src/pages/research-assistant/index.tsx
- web/src/types/ResearchAssistant.ts
- web/styles/components/MessageBubble.module.scss
- web/styles/components/ResearchAssistant.module.scss
- web/styles/components/ResearchAssistantWindow.module.scss
- Adds frontend components to integrate with the VRA backend /chats route
- the VRA is accessible at /research-assistant 
- Most styles are hard-coded and not using DS base styles
- Updates the /chats API route to return a json object for `results`
> Setup initial frontend VRA

- etl-pipeline/logger.py
- etl-pipeline/processes/grin/download.py
- etl-pipeline/processes/grin/ingest.py
- etl-pipeline/processes/record_ingestor.py
- etl-pipeline/processes/utils.py
- etl-pipeline/scripts/__init__.py
- etl-pipeline/scripts/grin_ingest_redrive.py
- etl-pipeline/utils/timer.py
- Adds better local logging formatting
- Adds timing logging
- Adds redrive script
`make unit; make functional; make integration`
> [SCHOL-73] GRIN ingest improvements

- etl-pipeline/processes/grin/conversion.py
- Continuously converts barcodes that are pending conversion
- If the process is daily, just check for newly added barcodes
> [SCHOL-75] Continuously convert barcodes

- etl-pipeline/services/sources/hathi_trust_service.py
- Increase field size limit by factor of 2
`pytest tests/integration/sources/test_hathi_trust_service.py`
> [NO-REF] Fix hathi trust integration test

- etl-pipeline/processes/grin/conversion.py
- etl-pipeline/processes/grin/grin_client.py
- 50k is the max number of barcodes queued for conversion
- If we run into the rate limit we just stop the batch requests and return early
> [NO-REF] Fix GRIN rate limiting

- web/package-lock.json
While setting up the frontend, I found that there is a critical dependency vulnerability. 
- Updates form-data with `npm audit fix` to fix:
`form-data uses unsafe random function in form-data for choosing boundary `
> Fix critical dependency vulnerability (form-data)

- .github/workflows/etl-pipeline-full-ci-cd.yaml
- etl-pipeline/processes/grin/conversion.py
- The conversion script looks like it stopped a few days ago. 
- Adding a conversion limit of 5k to prevent trying to convert 10s of thousands of book at once.
> [NO-REF] Set conversion limit

- etl-pipeline/tests/functional/processes/grin/download_test.py
I had to do a setup and teardown to delete the existing test barcode, so it can be downloaded again for each consecutive  test run. 
pytest -s tests/functional/processes/grin/download_test.py
> Fix download test

- etl-pipeline/managers/muse.py
- Uses xpath to select cards with div/li elements that represent titles
`make integration`
> [NO-REF] Fix MUSE card parsing
